import React from "react";
import "./ao-einheit3.css";
import "./ao-einheit5.css";
import "./ao-einheit6.css";
import "./ao-einheit7.css";

const Box=({children,ton="blau"})=><div className={`ao3-box ao3-box--${ton}`}>{children}</div>;
const Note=({children,ton="yellow"})=><div className={`ao5-note ao5-note--${ton}`}>{children}</div>;
const Arrow=()=> <span className="ao3-arrow">↓</span>;

function Anfechtung351(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Besonderheiten im Einspruchsverfahren · § 351 Abs. 1 AO</h3><Note ton="pink"><b>Gilt nur bei Einspruch gegen Änderungsbescheid.</b> Der vorherige Bescheid ist wirksam + unanfechtbar; grundsätzlich kann nur die Änderung angefochten werden.</Note><div className="ao7-warning">⚠ Schritt 1 · für jeden Fehler, den das FA gerade korrigiert hat, und für alles, was der Stpfl. zusätzlich korrigiert haben will: Korrekturformel prüfen.</div><div className="ao7-branch"><div className="ao7-card ao7-card--green"><h4>Ja · Korrekturformel erfüllt</h4><p>Berücksichtigung nach Quellenkarte <b>unbeschränkt möglich</b>.</p></div><div className="ao7-branch__mid">↔</div><div className="ao7-card ao7-card--red"><h4>Nein</h4><p>Nur zu berücksichtigen in demselben Umfang, in dem der Betrag nach <b>§ 177 Abs. 1/2 AO</b> hätte berücksichtigt werden können.</p></div></div><div className="ao7-warning">⚠ Schritt 2 · Ober-/Untergrenze bilden · 1:1 wie bei § 177 AO („Was hätte § 177 AO gemacht?“)</div></div>}

function Fall351(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Originalfall · § 351 Abs. 1 AO + Saldierungsrahmen</h3><div className="ao7-case"><h4>Ausgangslage</h4><p>ESt 2024 · Steuer <b>10.000 €</b> · endgültig. Änderungsbescheid 3.7.2026 korrigiert Honorar + WK; Einspruch begehrt zusätzlich Feststellungsverlust + VuV. Quelle notiert reguläre FF <b>31.12.2029</b>.</p></div><table className="ao7-table"><thead><tr><th>Punkt</th><th>Korrekturweg laut Quelle</th><th>Steuerwirkung</th></tr></thead><tbody><tr><td>Honorar</td><td>§ 173 Abs. 1 Nr. 1 AO</td><td className="ao7-money-up">↑ 3.000 €</td></tr><tr><td>Zahlendreher / WK</td><td>§ 129 S. 1 AO</td><td className="ao7-money-up">↑ 1.500 €</td></tr><tr><td>Feststellungsverlust</td><td>§ 175 Abs. 1 Nr. 1 AO</td><td className="ao7-money-down">↓ 2.100 €</td></tr><tr><td>VuV · Variante a</td><td>eine Tatsache / neue Einkunftsquelle</td><td className="ao7-money-down">↓ 2.700 €</td></tr><tr><td>VuV · Variante b</td><td>eine Tatsache / neue Einkunftsquelle</td><td className="ao7-money-down">↓ 6.000 €</td></tr></tbody></table><div className="ao7-limits"><div className="ao7-limit ao7-limit--up"><span>Obergrenze</span><strong>14.500 €</strong></div><div className="ao7-limit-mid">Steuer<br/><b>10.000 €</b></div><div className="ao7-limit ao7-limit--down"><span>Untergrenze</span><strong>7.800 €</strong></div></div><div className="ao7-cols"><div className="ao7-card ao7-card--green"><h4>Ergebnis Einspruch a)</h4><p><b>Abhilfebescheid: 9.700 €</b></p></div><div className="ao7-card ao7-card--yellow"><h4>Ergebnis Einspruch b)</h4><p><b>EE: Steuer auf 7.800 €</b>; im Übrigen als unbegründet zurückgewiesen.</p></div></div></div>}

const wdRows=[
["Leichte Krankheit / geplanter Eingriff","","✕"],["plötzliche, schwere Krankheit (z.B. Koma)","✓",""],["schwere Krankheit / Tod Angehöriger","✓",""],["Urlaub 8 Wochen","","✕"],["Urlaub 21 Tage","","✕"],["Urlaub 30 Tage bis 2 Tage vor Fristende","✓",""],["Einspruch bei falschem FA","","✕"],["Verschulden anderer Person","Bote","Vertreter"],["Irrtum bei Fristberechnung","Laie","Profi"]
];
function WiedereinsetzungGrund(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">II. Wiedereinsetzung · § 110 AO</h3><div className="ao7-warning">⚠ Zuerst sauber prüfen, ob Frist wirklich versäumt ⚠</div><p className="ao7-remember">§ 110 AO beginnt i.d.R. erst ab Punkt 8/35 im Examen.</p><div className="ao7-step"><i>1</i><div><b>Gesetzliche Frist</b><p>≠ behördliche Frist. Quelle nennt: Einspruchsfrist, Klagefrist § 56 FGO, Wiedereinsetzungsfrist, Ausschlussfrist § 364b AO. <span className="ao7-cross">Nicht: Abgabefrist StErkl.</span> → § 109 AO.</p></div></div><div className="ao7-step"><i>2</i><div><b>ohne Verschulden versäumt</b><p>Jede Form von Verschulden reicht, z.B. leichte Fahrlässigkeit. Viel strenger als § 173 Abs. 1 Nr. 2 AO; bei Fachkundigen strenger als beim Laien.</p></div></div><Note ton="green">Grundgedanke der Quelle: Frist selbst im Blick behalten; bei Abwesenheit Vertreter/Boten organisieren (bei normalem Stpfl. Urlaub erst ab ca. &gt; 6 Wochen als Problemhinweis in der Mitschrift).</Note></div>}
function Fall9(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Fall 9 · Verschulden an der Versäumung der Einspruchsfrist?</h3><table className="ao7-table"><thead><tr><th>Situation</th><th>≠ Verschulden</th><th>Verschulden</th></tr></thead><tbody>{wdRows.map(([s,a,b])=><tr key={s}><td>{s}</td><td className="ao7-yes">{a}</td><td className="ao7-no">{b}</td></tr>)}</tbody></table><Note>Die Quelle trägt bei „Verschulden anderer Person“ <b>Bote</b> links und <b>Vertreter</b> rechts ein; beim Fristberechnungsirrtum <b>Laie</b> links und <b>Profi</b> rechts.</Note><div className="ao7-source">Digitale Tabelle nach Fall 9 und der anschließenden „Übersicht Verschulden § 110 Abs. 1 AO“.</div></div>}
function WiedereinsetzungAntrag(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">§ 110 Abs. 2 AO · Wiedereinsetzungsfrist und Verfahren</h3><div className="ao7-rule"><b>innerhalb von 1 Monat nach Wegfall des Hindernisses</b></div><div className="ao7-cols"><div className="ao7-card ao7-card--red"><h4>Immer!</h4><p><b>S. 3: Handlung nachgeholt!</b></p></div><div className="ao7-card ao7-card--yellow"><h4>Meistens!</h4><p><b>S. 2: Gründe für unverschuldete Versäumnis genannt.</b> Ausnahme der Quelle: FA kennt Gründe bereits, z.B. Eingangsstempel falsches FA.</p></div></div><div className="ao7-card ao7-card--green"><h4>Nie zwingend!</h4><p><b>S. 4: Antrag</b> – Wiedereinsetzung kann nach der Quelle auch ohne ausdrücklichen Antrag gewährt werden.</p></div></div>}
function ZweiEinsprueche(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Zwei Einsprüche in derselben Sache</h3><div className="ao7-timeline"><div className="ao7-time"><b>7.7.02</b><span>EStB 01 trotz Empfangsvollmacht an Stpfl.</span></div><div className="ao7-time"><b>3.9.02</b><span>Stpfl. Einspruch</span><small>SFFEB</small></div><div className="ao7-time"><b>4.11.02</b><span>Weiterleitung EStB an Berater</span><small>§ 8 VwZG analog = Heilung</small></div><div className="ao7-time"><b>2.12.02</b><span>Berater Einspruch</span></div></div><div className="ao7-rule">Erster Einspruch zulässig und Verfahren noch läuft → zweiter Einspruch nach Quellenkarte <b>unzulässig</b>; kein weiteres Rechtsschutzbedürfnis.</div><p className="ao7-remember">Merke: Bei 2 Einsprüchen in derselben Sache immer zuerst den ersten prüfen!</p></div>}

function GuEBekanntgabe(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Bekanntgabe von GuE-Bescheiden · §§ 183 / 183a AO</h3><div className="ao7-gue-head">Inhaltsadressaten sind die G'er (§ 179 Abs. 2 S. 1 AO), aber Empfänger …</div><div className="ao7-gue-tree"><div className="ao7-gue-side"><div><h4>Rechtsfähige PersV</h4><b>§ 14a Abs. 2 Nr. 2</b></div><div><b>§ 183 AO</b></div><div><b>§ 183 Abs. 1 S. 1 + 2 AO</b><p>Bekanntgabe an PersV mit <span style={{color:"var(--y)"}}>Wirkung für alle</span>, wenn Hinweis S. 2 enthalten.</p></div></div><div className="ao7-gue-middle">🐑</div><div className="ao7-gue-side"><div><h4>Nicht rechtsfähige PersV</h4><b>§ 14a Abs. 3 Nr. 3</b></div><div><b>§ 183a AO</b></div><div><b>Empfangsbevollm. § 183a Abs. 1 S. 1?</b><p className="ao7-yes">Ja → Bekanntgabe nur an diesen mit Wirkung für alle.</p><p className="ao7-no">Nein → weitere Quellenverzweigung über Auswahl/Einzelbekanntgabe.</p></div></div></div><div className="ao7-two-col-note"><div><b>G'er ausgeschieden?</b><p>Bekanntgabe nach Quellenkarte weiter an PersV, solange gegenüber FA nicht widersprochen; § 183 Abs. 1.</p></div><div><b>Einzeln zustellen?</b><p>Solange dem FA nicht bekannt: Einzelbekanntgabe. Sobald dem FA bekannt, greifen die besonderen §-183a-Folgen; der Quellenblock behandelt konkludenten Widerspruch und das Ende der Vertretungswirkung.</p></div></div><Note ton="pink"><b>War Beteiligter tot:</b> Quelle notiert Teilnichtigkeit § 125 Abs. 4 → Richtigstellungsbescheid.</Note></div>}

function GuEEinspruch(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">IV. Einspruchsbefugnis GuE · § 352 AO</h3><div className="ao7-warning">Bei GuE-Bescheiden sind nur bestimmte Personen einspruchsbefugt! → Bei allen anderen: <span className="ao7-no">Einspruch unzulässig!</span></div><div className="ao7-branch"><div className="ao7-card ao7-card--green"><h4>Rechtsfähige PersV</h4><p>Quelle: PersV selbst handelnd durch ihren Vertreter <b>§ 34 AO</b>; § 352 Abs. 1 Nr. 1.</p></div><div className="ao7-branch__mid">§ 352</div><div className="ao7-card ao7-card--yellow"><h4>Nicht rechtsf. PersV</h4><p>Quellenzweig abhängig davon, ob ein Empfangsbevollmächtigter bestellt/bekannt ist; sonst weitere §-352-Alternativen.</p></div></div><div className="ao7-rule"><b>Zusatzbefugnisse</b><br/>Nr. 3: Streitende &amp; Ausgeschiedene · Nr. 4: jeder bzgl. „Ob“ und Umfang · Nr. 5: jeder für seinen Sonderbereich <span style={{color:"var(--p)"}}>→ Teilbefugnisse</span></div></div>}

function KorrekturSonstigerVA(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Korrektur sonstiger VA</h3><div className="ao7-va-branches"><div className="blue"><b>§ 129 AO</b><p>offenbare Unrichtigkeit</p></div><div className="yellow"><b>§ 130 AO</b><p>rechtswidrig · Rücknahme VA</p></div><div className="green"><b>§ 131 AO</b><p>rechtmäßig · Widerruf VA</p></div></div><div className="ao7-game"><h4>Spielregeln:</h4><p>① Beurteilung nur auf <b>Erlasszeitpunkt</b></p><p>② Beurteilung aus <b>allwissender Sicht</b></p></div><div className="ao7-flow"><div className="ao7-node"><b>Stpfl.</b><small>hält neuen Umstand / „Los“</small></div><span>→</span><div className="ao7-node"><b>FA</b><small>entscheidet nach Rechtslage am Erlasszeitpunkt</small></div></div></div>}

function SimpleFall({nr,title,facts,result,norm}){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Fall {nr} · {title}</h3><div className="ao7-case"><h4>Sachverhalt</h4><p>{facts}</p><div className="ao7-case-result">Quellenlösung: {result}</div></div><div className="ao7-rule">{norm}</div></div>}
function Fall10(){return <SimpleFall nr="10" title="Stundung · Jackpot schon vorher" facts="Stundung wegen Zahlungsunfähigkeit; auf dem Rückweg findet der Stpfl. einen Lottoschein und erkennt, dass er bereits am Vortag den Euro-Jackpot geknackt hatte." result="Ja, Rücknahme möglich; handschriftlich: innerhalb 1 Jahr seit Kenntnis." norm="§ 130 Abs. 2 Nr. 3 + Abs. 3 AO"/>}
function Fall11(){return <SimpleFall nr="11" title="Stundung · Jackpot erst am Folgetag" facts="Bei Erlass liegen die Stundungsgründe zutreffend vor; erst am Folgetag knackt der Stpfl. den Euro-Jackpot." result="Ja, Widerruf nach Quellenweg möglich." norm="§ 131 AO · Fristbezug der Quelle zu § 130 Abs. 3 AO"/>}
function Fall12(){return <SimpleFall nr="12" title="500 € Verspätungszuschlag irrtümlich" facts="Verspätungszuschlag 500 €, obwohl Erklärung nicht verspätet war; zwei Monate später Aufhebungsantrag." result="Kein zwingender Aufhebungsanspruch; Quelle betont § 130 Abs. 1 AO als Kann-Vorschrift." norm="§ 130 Abs. 1 AO („kann“)"/>}
function Fall13(){return <SimpleFall nr="13" title="Haftungsbescheid nach vollständiger Zahlung" facts="Nach Erlass des Haftungsbescheids wird die zugrunde liegende Steuerschuld vollständig durch den Steuerschuldner bezahlt." result="Ja, Aufhebung/Widerruf nach § 131 Abs. 1 AO möglich." norm="§ 131 Abs. 1 AO"/>}

function PlanABC(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Prüfungsreihenfolge · vermeintlich fehlerhafter VA</h3><div className="ao7-plan"><div className="a"><h4>Plan A</h4><p>Prüfe, ob Einspruch eingelegt wurde oder noch eingelegt werden kann.</p><b>Ja → Erfolgsaussichten / Erfolgsformel</b></div><div className="arr">→</div><div className="b"><h4>Plan B</h4><p>VA im Korrekturverfahren aufheben/ändern?</p><p>Steuerbescheid: Korrekturformel · sonstiger VA: <b>§§ 129–131 AO</b>.</p></div><div className="arr">→</div><div className="c"><h4>Plan C</h4><p>Saldierung nach <b>§ 177 AO</b>, soweit noch möglich.</p></div></div></div>}

function Steuerhinterziehung(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Steuerhinterziehung · Prüfschema § 370 AO</h3><div className="ao7-stairs"><div className="ao7-stair"><b>① Objektiver Tatbestand</b><span>Start</span></div><div className="ao7-stair"><b>1) Tathandlung</b><span>§ 370 Abs. 1 Nr. 1 oder Nr. 2</span></div><div className="ao7-stair"><b>2) Kausaler Taterfolg</b><span>Steuervorteil / Steuerverkürzung</span><small>Quelle: zu viel VorSt · zu niedriger F-Bescheid · zunächst keine Steuer festgesetzt</small></div><div className="ao7-stair"><b>3) subjektiver Teil</b><span>weitere sichtbare Quellenstationen</span></div><div className="ao7-stair"><b>4) weitere Strafbarkeitsstufen</b><span>Qualifikationen / Versuch nach den markierten Gesetzesstellen</span></div></div><Note ton="red">Die digitale Treppe übernimmt nur die in der Quelle sichtbar aufgebauten Stationen; nicht lesbare/angeschnittene Fortsetzungen werden nicht ergänzt.</Note></div>}
function Vollstreckung(){return <div className="ao3-sheet ao7-sheet"><h3 className="ao3-title">Vollstreckung · Wiederholung</h3><div className="ao7-lanes"><section className="ao7-lane"><h4>Überprüfung allgemeine Vollstreckungsvoraussetzungen:</h4><div className="ao7-lane-track">{["§ 249 (1)","§ 251 (1)","§ 361","§ 254 (1)","§ 220","§ 259"].map(x=><span key={x} className="ao7-lawbox">{x}</span>)}</div></section><section className="ao7-lane"><h4>Überprüfung der jeweiligen Vollstreckungsmaßnahme:</h4><div className="ao7-lane-track">{["§ 281 (1)","§ 286","§ 263","§ 295","§ 286 (2)"].map(x=><span key={x} className="ao7-lawbox">{x}</span>)}</div></section></div></div>}

export const AO7_SCHEMATA={
 "ao7-351-anfechtung":Anfechtung351,
 "ao7-fall-351":Fall351,
 "ao7-110-voraussetzungen":WiedereinsetzungGrund,
 "ao7-fall9-verschulden":Fall9,
 "ao7-110-antrag":WiedereinsetzungAntrag,
 "ao7-fall-zwei-einsprueche":ZweiEinsprueche,
 "ao7-gue-bekanntgabe":GuEBekanntgabe,
 "ao7-gue-einspruchsbefugnis":GuEEinspruch,
 "ao7-korrektur-sonstiger-va":KorrekturSonstigerVA,
 "ao7-fall10":Fall10,
 "ao7-fall11":Fall11,
 "ao7-fall12":Fall12,
 "ao7-fall13":Fall13,
 "ao7-plan-abc":PlanABC,
 "ao7-steuerhinterziehung":Steuerhinterziehung,
 "ao7-vollstreckung":Vollstreckung,
};
export const ao7SchemaIds=Object.keys(AO7_SCHEMATA);
