import React from "react";
import "./ao-einheit3.css";

const Box=({children,ton="blau",className=""})=><div className={`ao3-box ao3-box--${ton} ${className}`}>{children}</div>;
const Arrow=()=> <span className="ao3-arrow">↓</span>;
const Tabs=({items})=><div className="ao3-tabs">{items.map((x,i)=><span key={i} className={x[1]||"pink"}>{x[0]}</span>)}</div>;

function FalschesFA(){return <div className="ao3-sheet"><h3 className="ao3-title">Eingang beim Anbringungs-Finanzamt · § 357 Abs. 2 AO</h3><div className="ao3-flow-row"><Box><b>Einspruch</b><small>tatsächlicher Eingang</small></Box><span>→</span><Box ton="pink"><b>richtige Anbringungsstelle?</b><small>§ 357 Abs. 2 AO</small></Box></div><div className="ao3-split"><section><b>JA</b><p>Fristwahrender Eingang möglich.</p></section><section><b>NEIN</b><p>nicht automatisch fristwahrend</p><Arrow/><p><strong>§ 110 AO</strong> prüfen</p><small>Quellenhinweis: Konnte noch rechtzeitig weitergeleitet werden?</small></section></div><div className="ao3-note">Backpfeifentheorie / doppelte Backpfeifentheorie: zuerst den angegriffenen VA und die zulässige Anbringungsstelle bestimmen.</div></div>}

function Beschwer(){return <div className="ao3-sheet"><h3 className="ao3-title">Einspruchsbefugnis · § 350 AO · „sich beschweren dürfen“</h3><div className="ao3-center"><Box ton="pink"><b>Ist der Einspruchsführer durch den VA beschwert?</b><small>§ 350 AO</small></Box><Arrow/></div><div className="ao3-checkgrid"><Box ton="gruen">Steuerbescheid mit eigener Belastung</Box><Box ton="gelb">Ehegatten-/Feststellungsfälle: persönliche Betroffenheit prüfen</Box><Box ton="blau">Dritter / Bevollmächtigter: eigene Beschwer nicht unterstellen</Box><Box ton="lila">Bindungswirkung und gesetzliche Vertretung gesondert prüfen</Box></div><div className="ao3-decision"><span>alle Zulässigkeitsvoraussetzungen erfüllt → <b>zulässig</b></span><span>sonst → per EE als <b>unzulässig</b> verwerfen</span></div><Tabs items={[["§ 347","pink"],["§ 357","pink"],["§ 355 / § 356 / § 357 II","pink"],["§ 110","pink"],["§ 352","pink"],["§ 350","pink"],["§ 358","pink"]]}/></div>}

function Begruendetheit(){return <div className="ao3-sheet"><h3 className="ao3-title">II. Begründetheit · wenn zulässig</h3><div className="ao3-four"><Box ton="pink"><i>1</i><b>Rechtmäßigkeit</b><span>des angefochtenen VA</span></Box><Box ton="pink"><i>2</i><b>Rechte des Stpfl. verletzt?</b></Box><Box ton="pink"><i>3</i><b>Anfechtungsbeschränkung</b><span>§ 351 Abs. 1 AO</span></Box><Box ton="pink"><i>4</i><b>Gesamtaufrollung</b><span>§ 367 Abs. 2 AO</span></Box></div><div className="ao3-card"><b>Einspruch – Begründetheit</b><p>Standardfehler: abgelaufene Festsetzungsfrist, materiell falsche Steuer, Festsetzung trotz V-Zuschlagsproblematik, fehlende Anhörung, fehlende Begründung, örtliche Zuständigkeit.</p><p><em>Keine automatische Rechtswidrigkeit:</em> fehlende RBB, falsche Korrekturbezeichnung bei anderweitig greifender Norm, geheilte Verfahrensfehler.</p></div><Tabs items={[["§ 125 / § 124(3)","orange"],["§ 124(1)","orange"],["§ 122(1)","orange"],["AEAO § 124","orange"],["§ 79(1)","orange"],["§ 347","pink"],["§ 357","pink"],["§ 110","pink"],["§ 352","pink"],["§ 350","pink"],["§ 358","pink"],["§ 100 FGO","rot"],["§ 351(1)","rot"],["§ 367(2)","rot"]]}/></div>}

function Besonderheiten(){return <div className="ao3-sheet"><h3 className="ao3-title">Besonderheiten im Einspruchsverfahren</h3><div className="ao3-procon"><section><h4>Vorteil</h4><ul><li>grds. keine Korrekturvorschrift erforderlich</li><li>Begründung kann nachgeholt / erweitert werden</li><li>Gesamtaufrollung des angefochtenen VA</li></ul></section><section><h4>Nachteil</h4><ul><li>FA darf auch andere Punkte ändern</li><li>höhere Steuer = <b>Verböserung</b></li><li>§ 367 Abs. 2 S. 2 AO beachten</li><li>Rücknahme § 362 AO prüfen</li></ul></section></div><div className="ao3-verb"><span className="donor">☺<br/>200 € Spender</span><span className="car">▰➜</span><div><b>Ausnahme der Quelle</b><p>Rücknahme schützt nicht, wenn dieselbe Verschlechterung ohnehin im Korrekturverfahren (Plan B) gedeckt wäre.</p><small>AEAO zu § 367 Nr. 2.2</small></div></div></div>}

function Erledigung(){return <div className="ao3-sheet"><h3 className="ao3-title">Ergebnis · § 367 AO</h3><div className="ao3-buttons"><Box ton="gruen"><b>100 % begründet</b><span>Abhilfebescheid</span></Box><Box ton="gelb"><b>teilweise begründet</b><span>ändern / herabsetzen + im Übrigen zurückweisen</span></Box><Box ton="rot"><b>0 % begründet</b><span>per EE als unbegründet zurückweisen</span></Box><Box ton="lila"><b>Verböserung</b><span>nachteilige Einspruchsentscheidung unter Voraussetzungen</span></Box></div><div className="ao3-card ao3-card--decision"><b>Einspruchsentscheidung</b><p>unzulässig · unbegründet · teilweise begründet · Verböserung</p></div></div>}

function PlanABC(){return <div className="ao3-sheet"><h3 className="ao3-title">Was tun, wenn ein vermeintlich fehlerhafter VA vorliegt?</h3><Box ton="pink"><b>Plan A</b><p>Prüfe, ob Einspruch eingelegt wurde oder noch werden kann.</p><span>JA → Erfolgsaussichten / Erfolgsformel</span></Box><Arrow/><Box ton="gruen"><b>Plan B</b><p>Kann der VA noch im Korrekturverfahren aufgehoben / geändert werden?</p><div className="ao3-mini-branch"><span>Korrekturvorschrift erlaubt?</span><span>Änderung möglich?</span><span>So.VA / §§ 129–132 AO?</span></div></Box><Arrow/><Box ton="gelb"><b>Plan C</b><p>Saldierung des Fehlers nach § 177 AO prüfen.</p></Box><div className="ao3-note">Verbleibender materieller Fehler erst nach Plan A / B / C bewerten.</div></div>}

function Korrekturformel(){return <div className="ao3-sheet"><h3 className="ao3-title">Plan B · Korrekturformel</h3><div className="ao3-formula"><span className="clock">◷<small>Festsetzungsfrist</small></span><b>+</b><span className="keys">🔑🔑🔑<small>Korrekturvorschriften</small></span></div><p className="ao3-centerline">Ein Fehler mit Auswirkung auf die festgesetzte Steuer darf außerhalb des Einspruchsverfahrens nur korrigiert werden, wenn für diesen Fehler:</p><div className="ao3-lockers">{[1,2,3,4].map((n)=><div key={n}><span>⋮</span><b>F{n}</b><i>🔒</i></div>)}</div><div className="ao3-locker-steps"><span>Fehler einzeln identifizieren</span><span>passenden Schlüssel suchen</span><span>Festsetzungsfrist je Fehler prüfen</span><span>nur passende Türen öffnen</span></div></div>}

function FFBeginn(){return <div className="ao3-sheet"><h3 className="ao3-title">1) Beginn · § 170 AO</h3><div className="ao3-split"><section><h4>Erklärungspflichtig</h4><p>z.B. ESt / USt nach den in der Quelle markierten Erklärungspflichten</p><Arrow/><b>§ 170 Abs. 2 AO</b><small>Anlaufhemmung</small></section><section><h4>andere Steuerarten</h4><p>Grundregel</p><Arrow/><b>§ 170 Abs. 1 AO</b></section></div><div className="ao3-note">Reihenfolge der Quelle: Steuerentstehung → Erklärungspflicht → Fristbeginn.</div></div>}

function FFDauer(){return <div className="ao3-sheet"><h3 className="ao3-title">2) Dauer · § 169 Abs. 2 AO</h3><div className="ao3-duration"><Box ton="blau"><span className="emoji">😇</span><b>sauber</b><strong>4 Jahre</strong></Box><Box ton="rot"><span className="emoji">😈</span><b>Steuerhinterziehung</b><strong>10 Jahre</strong></Box><Box ton="gelb"><span className="emoji">☀</span><b>leichtfertige Verkürzung</b><strong>5 Jahre</strong></Box></div></div>}

function FFEnde(){return <div className="ao3-sheet"><h3 className="ao3-title">3) Reguläres Ende</h3><div className="ao3-flow-row"><Box ton="gruen"><b>Beginn</b><small>§ 170 AO</small></Box><span>+</span><Box ton="gruen"><b>Dauer</b><small>§ 169 Abs. 2 AO</small></Box><span>→</span><Box ton="gelb"><b>reguläres Ende</b><small>§ 169 Abs. 1 AO · §§ 187/188 BGB</small></Box></div><div className="ao3-big-note">Prüfe <u>nur wenn</u> die reguläre Festsetzungsfrist bereits abgelaufen wäre …</div><Arrow/><Box ton="gruen"><b>4) Ablaufhemmungen · § 171 AO</b></Box></div>}

function Korrekturpaerchen(){return <div className="ao3-sheet"><h3 className="ao3-title">Korrekturpärchen</h3><div className="ao3-big-note">Suche, wenn reguläre 4-Jahres-FF abgelaufen, nach möglichst vielen passenden Korrekturpärchen.</div><div className="ao3-pairs"><section><b>Ereignis / Fehler</b><b>Ablaufhemmung</b><b>♥</b><b>Korrekturvorschrift</b></section><section><span>Schreib-/Rechenfehler</span><span>§ 171 Abs. 2 S. 1 AO</span><b>♥</b><span>§ 129 AO</span></section><section><span>Schreib-/Rechenfehler</span><span>§ 171 Abs. 2 S. 2 AO</span><b>♥</b><span>§ 173a AO</span></section><section><span>Antrag vor Ablauf FF</span><span>§ 171 Abs. 3 AO</span><b>♥♥♥</b><span>§ 164 Abs. 2 / § 173 / …</span></section><section><span>zulässiger Einspruch</span><span>§ 171 Abs. 3a AO</span><b>♥</b><span>§ 350 ff. AO / Änderungsumfang</span></section></div><Tabs items={[["§ 169","gruen"],["§ 170","gruen"],["§ 164(2)","gruen"],["§ 171","gruen"],["§ 171(2)","gruen"],["§ 173","gruen"],["§ 173a","gruen"],["§ 171(3)","gruen"],["§ 171(3a)","gruen"],["§ 171(4)","gruen"],["§ 175","gelb"],["AEAO § 175.12","pink"]]}/></div>}

function Ablaufhemmungen(){return <div className="ao3-sheet"><h3 className="ao3-title">Ablaufhemmungen · § 171 AO</h3><div className="ao3-split"><section><h4>§ 171 Abs. 3a AO</h4><b>Voraussetzung: zulässiger Einspruch (Plan A)</b><p>Quellenregel: vollumfängliche Hemmung für alle Fehler, die bei Postaufgabe des angefochtenen Bescheids noch nicht verjährt waren.</p><div className="ao3-timeline"><span>FF</span><i>────────</i><span className="target">◎ Einspruch</span></div></section><section><h4>§ 171 Abs. 4 AO</h4><b>Hemmung durch Außenprüfung</b><p>1. wirksame Prüfungsanordnung nach § 196 AO vor Ablauf der FF.</p><div className="ao3-mini-branch"><span>Beginn der AP vor Ablauf FF</span><span>oder</span><span>Verschiebung des Beginns auf Antrag / nach Quellenregel</span></div></section></div></div>}

export const AO3_SCHEMATA={
 "ao3-falsches-fa":FalschesFA,
 "ao3-beschwer":Beschwer,
 "ao3-begruendetheit":Begruendetheit,
 "ao3-einspruch-besonderheiten":Besonderheiten,
 "ao3-einspruch-erledigung":Erledigung,
 "ao3-plan-abc":PlanABC,
 "ao3-korrekturformel":Korrekturformel,
 "ao3-ff-beginn":FFBeginn,
 "ao3-ff-dauer":FFDauer,
 "ao3-ff-ende":FFEnde,
 "ao3-korrekturpaerchen":Korrekturpaerchen,
 "ao3-ablaufhemmungen":Ablaufhemmungen,
};
export const ao3SchemaIds=Object.keys(AO3_SCHEMATA);
