import React from "react";
import "./ao-einheit3.css";
import "./ao-einheit5.css";
import "./ao-einheit6.css";

const Box=({children,ton="blau",className=""})=><div className={`ao3-box ao3-box--${ton} ${className}`}>{children}</div>;
const Arrow=()=> <span className="ao3-arrow">↓</span>;
const Note=({children,ton="yellow"})=><div className={`ao5-note ao5-note--${ton}`}>{children}</div>;
const Tabs=({items})=><div className="ao5-tabs">{items.map(([x,t],i)=><span key={`${x}-${i}`} className={t}>{x}</span>)}</div>;

function Verschulden173(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">§ 173 AO · Stufe 4: Ermittlungsfehler ↔ grobes Verschulden</h3><div className="ao6-cols"><section className="ao6-col ao6-col--green"><h4>④ kein Ermittlungsfehler FA</h4><b>AEAO § 173 Nr. 4</b><p>Quelle: nur dann, wenn der Stpfl. die Erklärung nach bestem Wissen &amp; Gewissen erstellt hat, sich dem FA aber insbesondere durch einen <b>RMS-Prüfhinweis</b> Zweifel hätten aufdrängen müssen und das FA diesen gar nicht nachgegangen ist.</p></section><section className="ao6-col ao6-col--red"><h4>④ kein grobes Verschulden Stpfl./StB</h4><b>AEAO § 173 Nr. 5</b><div className="ao6-cols"><div><strong style={{color:"var(--g)"}}>kein grobes Verschulden</strong><ul><li>Versehen / Vergessen</li><li>Schreibfehler</li><li>Rechenfehler</li><li>Übertragungsfehler</li><li>bloße stl. Unkenntnis &amp; Problem auch nicht erkannt</li></ul></div><div><strong style={{color:"var(--r)"}}>grobes Verschulden</strong><ul><li>Vorsatz („bewusst“)</li><li>Unordnung / „3 Promille / Fieber“</li><li>Erklärungsvordrucke inkl. aller Hinweise nicht sorgfältig durchgearbeitet</li></ul></div></div></section></div><Arrow/><div className="ao6-rulebox"><b>§ 173 Abs. 1 Nr. 2 S. 2 AO</b><br/><strong>Verschulden ist unbeachtlich</strong>, wenn Zusammenhang mit neuer Tatsache i.S.d. § 173 Abs. 1 Nr. 1 AO.</div><div className="ao6-branch"><div className="ao6-mini-card"><b>Einkauf desselben PKW</b><small>Nr. 2</small></div><div className="ao6-branch__mid">↔</div><div className="ao6-mini-card"><b>Verkauf desselben PKW</b><small>Nr. 1</small></div></div><Note ton="green">Quellenbeispiel S. 7: PKW-Händler – Einkauf und Verkauf desselben PKW.</Note></div>}

function Rechtserheblichkeit173(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">§ 173 AO · Stufe 5 Rechtserheblichkeit + Stufe 6 Änderungssperre</h3><Box ton="gelb"><b>⑤ Rechtserheblichkeit · AEAO § 173 Nr. 3</b><small>Bei Änderung von Rechtsprechung / Verwaltungsauffassung (z.B. EStR, UStAE) prüfen, ob die Tatsache auch schon nach der vorherigen Rechtsprechung / Verwaltungsauffassung berücksichtigt worden wäre.</small></Box><h4 className="ao5-hand" style={{textAlign:"center",marginTop:18}}>War diesbezüglich schon ein Verfahren beim BFH anhängig?</h4><div className="ao6-branch"><div className="ao6-mini-card"><b>§ 165 Abs. 1 S. 2 Nr. 4 AO</b><small>vorläufige Festsetzung</small></div><div className="ao6-branch__mid">oder</div><div className="ao6-mini-card"><b>Einspruch &amp; Ruhen des Verfahrens</b><small>§ 363 Abs. 2 AO</small></div></div><div className="ao6-ap-lock"><b>⑥ keine Änderungssperre · § 173 Abs. 2 AO</b><p>Nach abgeschlossener AP (ÄndB / Nullmitteilung) darf nach § 173 Abs. 1 AO nach der Quelle nur noch geändert werden, <strong>soweit StHi</strong>.</p></div><div className="ao3-card"><b>NEUE TATSACHEN</b><p>Native Merkkarte nach PDF-S. 12: die §-173-Prüfung bleibt in Stufen aufgebaut; Rechtserheblichkeit und Änderungssperre sind eigene Stationen.</p></div></div>}

const matrix172=[
["Schreib-/Rechenfehler","§ 171 Abs. 2 S. 1 AO","§ 129 AO"],["Schreib-/Rechenfehler Stpfl.","§ 171 Abs. 2 S. 2 AO","§ 173a AO"],["Antrag vor Ablauf FF","§ 171 Abs. 3 AO","§ 164(2) / § 173(1) / …"],["zulässiger Einspruch","§ 171 Abs. 3a AO","§ 367 Abs. 2 S. 1 AO"],["AP + wirks. PA","§ 171 Abs. 4 AO","§ 164(2) / § 173(1) / …"],["SteuFa / StraBuSt","§ 171 Abs. 5 AO","§ 172(1) Nr. 2c + § 173(1); nicht: § 164 AO"],["StHi","§ 169 Abs. 2 S. 2 AO","§ 172(1) Nr. 2c + § 173(1); nicht: § 164 AO"],["Beichte","§ 171 Abs. 9 AO","§ 173(1) AO; nicht: § 172(1) Nr. 2a AO"],["wirks. F-Bescheid","§ 171 Abs. 10 S. 1 AO","§ 175 Abs. 1 Nr. 1 AO"],["Annahme Erbe","§ 171 Abs. 12 AO","§ 173 Abs. 1 AO"],["Erstattung","§ 171 Abs. 14 AO","— (EStbescheid)"],["Vorläufige Festsetzung","§ 171 Abs. 8 S. 1 AO","§ 165 Abs. 2 S. 1 AO"],["Vorläufige Festsetzung","§ 171 Abs. 8 S. 2 AO","§ 165 Abs. 2 S. 2 AO"]
];
function PairTable({rows=matrix172}){return <div className="ao5-pairs"><section><b>Ereignis</b><b>Frist-/Hemmungsnorm</b><b>♥</b><b>Korrektur / Folge</b></section>{rows.map(([a,b,c],i)=><section key={i}><span>{a}</span><span>{b}</span><b className="ao5-heart">{c.startsWith("—")?"–":"♥"}</b><span>{c}</span></section>)}</div>}
function Schema172(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">§ 172 AO · Zustimmung / schlichte Änderung / soweit StHi</h3><div className="ao6-172flow"><div className="ao6-172row"><strong>↑ zu Lasten</strong><div><b>§ 172 Abs. 1 Nr. 2a AO</b> · nur wenn der Stpfl. zustimmt. <span className="ao6-crossed">nicht: Anzeige § 153 AO</span><br/><small>Quelle: formloser außergerichtlicher Rechtsbehelf.</small></div></div><div className="ao6-172row"><strong style={{color:"var(--g)"}}>↓ zu Gunsten</strong><div><b>Antrag auf schlichte Änderung</b> nur innerhalb der Einspruchsfrist (§§ 356, 357, § 110 AO). Nach der Quelle innerhalb der Frist nicht nur stellen, sondern <u>dem Grunde und der Höhe nach konkretisieren</u>.</div></div></div><Note ton="pink"><b>Cave:</b> vorrangig Auslegung/Umdeutung in möglichst viele Einsprüche, außer telefonisch. Nachteile der schlichten Änderung laut Quelle: keine AdV wie beim Einspruch; nach Ablauf der Rechtsbehelfsfrist nicht erweiterbar.</Note><h4 className="ao5-hand">§ 172 Abs. 1 Nr. 2c AO · soweit StHi</h4><p>Umfang der StHi nach dem Kompensationsverbot § 370 Abs. 4 S. 3 AO: Nur bewusst auch nicht erklärte Ausgaben gehören nach der Quellenskizze zum Teil, alles andere nicht.</p><div className="ao6-comp"><div className="included"><b>BE verschwiegen</b><br/>+ 100</div><div className="included"><b>BA verschwiegen</b><br/>− 70</div><div className="excluded"><b>Spenden verschwiegen</b><br/>− 40</div></div><PairTable/></div>}

function Grundlagen175(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Anpassung EStB an F-Bescheid · § 175 Abs. 1 Nr. 1 AO</h3><div className="ao5-flow"><Box ton="blau"><b>Erlass / Aufhebung / Änderung</b><small>AEAO § 175 Nr. 1.3</small></Box><span>→</span><Box ton="gruen"><b>Grundlagenbescheid</b><small>§ 171 Abs. 10 AO</small></Box><span>→</span><div className="ao6-inf">∞</div></div><p className="ao5-hand" style={{textAlign:"center"}}>Bindungswirkung ∞ für den EStB</p><div className="ao6-checks"><div className="ao6-check"><b>① Prüfe § 182 Abs. 1 S. 1 AO</b></div><div className="ao6-branch__mid">→</div><div className="ao6-check"><b>② Prüfe Wirksamkeitsformel F-Bescheide</b></div></div><Note ton="green"><b>RF:</b> Anpassung EStB an F-Bescheid (∞); bei ersatzloser Aufhebung nennt die Quelle die Befugnis zur eigenen Überprüfung der Einkünfte und zur entsprechenden Änderung.</Note><div className="ao6-rulebox">Ablaufhemmung <b>§ 171 Abs. 10 S. 1 AO</b> ♥ <b>§ 175 Abs. 1 Nr. 1 AO</b></div><Note><b>Bei Übersehen / unrichtiger Auswertung einer ESt-Feststellungsmitteilung:</b> Quelle zeigt § 175 Abs. 1 Nr. 1 AO „unendlich oft“ und zusätzlich § 129 AO ♥ § 171 Abs. 2 S. 1 AO.</Note></div>}

function Rueckwirkend175(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Rückwirkendes Ereignis · § 175 Abs. 1 Nr. 2 AO</h3><div className="ao6-retro"><div><b>ESt 01</b></div><div><b>02</b></div><div><b>03</b></div><div><b>04</b></div><div className="event"><b>Ereignis 05</b><small>wirkt zurück</small></div></div><div className="ao5-flow"><Box ton="gelb"><b>Eintritt rückwirkendes Ereignis</b><small>AEAO § 175 Nr. 2.3 / 2.4</small></Box><span>→</span><Box ton="gruen"><b>punktuelle Änderung ↑ / ↓</b><small>§ 175 Abs. 1 Nr. 2 AO</small></Box><span>+</span><Box ton="pink"><b>punktuelle FF</b><small>§ 175 Abs. 1 S. 2 AO</small></Box></div><div className="ao6-cols"><section className="ao6-col ao6-col--green"><h4>Rückwirkung möglich</h4><p>Fälle nach AEAO § 175 Nr. 2.4; Quellenkarte nennt auch den späteren Wegfall von Voraussetzungen einer Steuerbefreiung.</p></section><section className="ao6-col ao6-col--red"><h4>Kein rückwirkendes Ereignis</h4><ul><li>Ereignis bereits vor Erlass des Bescheids → stattdessen § 173 AO prüfen.</li><li>Änderung von Rechtsprechung oder Gesetz.</li><li>nachträgliche Erteilung/Vorlage einer Bescheinigung, § 175 Abs. 2 S. 2 AO.</li></ul></section></div><PairTable rows={[...matrix172,["Rückw. Ereignis","§ 175 Abs. 1 S. 2 AO","§ 175 Abs. 1 Nr. 2 AO"],["eDaten","§ 171 Abs. 10a AO","§ 175b Abs. 1 / 2 AO"]]}/></div>}

function Saldierung177(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Plan C · Saldierung nach § 177 AO</h3><div className="ao6-puzzle"><div className="ao6-piece ao6-piece--bad">Plan B ✕<br/><small>nicht mehr änderbarer Fehler</small></div><div className="ao6-piece ao6-piece--good">Plan B ✓<br/><small>gegenläufiger noch änderbarer Fehler</small></div></div><Note ton="red"><b>Keine eigenständige Korrekturvorschrift:</b> § 177 ermöglicht die Saldierung nicht mehr änderbarer Fehler mit gegenläufigen noch änderbaren Fehlern.</Note><div className="ao5-steps"><div className="ao5-step"><i>1</i><div><b>Materieller Fehler · § 177 Abs. 3 AO</b><p>Fehler mit Auswirkung auf die Höhe der Steuer, der aber nicht mehr nach Plan B korrigiert werden kann – Quelle nennt: FF abgelaufen und/oder keine KV erfüllt.</p></div></div><div className="ao5-step"><i>2</i><div><b>Gegenläufige Korrekturmöglichkeit eines anderen Fehlers</b><p>„was zum Radieren“</p></div></div></div><div className="ao6-rulebox"><b>RF:</b> Berücksichtigung des materiellen Fehlers bis zur Höhe der gegenläufigen Korrekturmöglichkeit – <strong>„soweit“</strong>.</div><div className="ao6-cols"><section className="ao6-col"><h4>🕷 Spinnenregel 1</h4><p>Mehrere materielle Fehler sind zu saldieren.</p><b>AEAO § 177 Nr. 4</b></section><section className="ao6-col"><h4>🕷 Spinnenregel 2</h4><p>Die noch änderbaren Fehler bilden Ober-/Untergrenze der Saldierung.</p><b>AEAO § 177 Nr. 2 + 3</b></section></div></div>}

function FallSaldierung(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Originalfall · ESt 2024 · Plan C / § 177 AO</h3><div className="ao5-fallbox"><h4>Ausgangslage</h4><p>EStB 2024 vom 10.11.2025 · Steuer <b>10.000 €</b> · endgültig · Quellensteuersatz 30 % · Frage: Änderung noch möglich am 3.7.2026?</p><Note>Kein §§ 164/165 AO, da EStB endgültig. Reguläre FF laut Quelle: m.A.d. 31.12.2029 (4 Jahre).</Note></div><table className="ao6-calc-table"><thead><tr><th>Fehler</th><th>Korrekturweg laut Quellenprüfung</th><th>Steuerwirkung</th></tr></thead><tbody><tr><td>Honorar 10.000 € nicht erklärt</td><td><span className="yes">✓ § 173 Abs. 1 Nr. 1 AO</span> / <span className="no">§ 172 Abs. 1 Nr. 2a AO</span></td><td className="up">↑ 3.000 €</td></tr><tr><td>Zahlendreher FA · WK 5.000 € zu hoch</td><td><span className="yes">✓ § 129 S. 1 AO</span> / <span className="no">§ 173a</span> / <span className="no">§ 173 Abs. 1 Nr. 1 AO</span></td><td className="up">↑ 1.500 €</td></tr><tr><td>F-Bescheid · Verlust 7.000 €</td><td><span className="yes">✓ § 175 Abs. 1 Nr. 1 AO</span> · Quelle notiert daneben § 129</td><td className="down">↓ 2.100 €</td></tr><tr><td>neues VuV-Objekt</td><td>1× Tatsache, da neue Einkunftsquelle · materieller Fehler § 177 Abs. 3 AO</td><td>a) ↓ 2.700 € · b) ↓ 6.000 €</td></tr></tbody></table><div className="ao6-cols"><section className="ao6-col"><h4>VuV Variante a</h4><p>Einnahmen 11.000 € · Ausgaben 20.000 € → Verlust 9.000 € → ↓ 2.700 €</p></section><section className="ao6-col"><h4>VuV Variante b</h4><p>Einnahmen 5.000 € · Ausgaben 25.000 € → Verlust 20.000 € → ↓ 6.000 €</p></section></div><div className="ao6-limits"><div className="ao6-limit-list"><div><b>Obergrenze</b><strong>14.500 €</strong></div><div className="up"><span>+ WK</span><span>↑ 1.500 €</span></div><div className="up"><span>+ Honorar</span><span>↑ 3.000 €</span></div><div><span>Steuer bisher</span><strong>10.000 €</strong></div><div className="down"><span>./. F-Bescheid</span><span>↓ 2.100 €</span></div><div><b>Untergrenze</b><strong>7.900 €</strong></div></div><div className="ao6-cube">§ 177<br/>Rahmen</div></div><div className="ao6-equations"><div>a) 10.000 + 3.000 + 1.500 − 2.100 − 2.700 = <b>9.700 €</b></div><div>b) 10.000 + 3.000 + 1.500 − 2.100 − 4.500 = <b>7.900 €</b></div></div><Note ton="red">Variante b: vom Fehler ↓ 6.000 € können nur ↓ 4.500 € in den Rahmen; <b>verbleibender materieller Fehler: ↓ 1.500 €</b>.</Note></div>}

function FallEinspruch351(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Abwandlung · Einspruch 7.8.2026 · § 351 AO</h3><div className="ao5-fallbox"><h4>Ausgangslage</h4><p>FA erlässt am <b>3.7.2026</b> geänderten EStB 2024; Honorar und WK werden korrigiert (<b>14.500 €</b>). Stpfl. legt am <b>7.8.2026</b> Einspruch ein und begehrt Verlust F-Bescheid &amp; VuV. Erfolgsaussichten?</p></div><h4 className="ao5-hand">I. Zulässigkeit</h4><div className="ao6-hourglass"><b>Rechtsbehelfsfrist</b><div className="ao6-hourglass__glass">⌛</div></div><div className="ao6-mnemonic"><span>SFFEB</span><i>↓</i><span>D.B.E.W.W</span><i>↓</i><span>N.O.N.B.H</span><small>= am 7.7.26</small></div><Note ton="pink">Die Quelle zeigt diese Buchstabenfolgen als Lernanker, ohne auf den vorliegenden Seiten eine ausgeschriebene Legende zu liefern. Deshalb bleiben sie digital bewusst unverändert.</Note><h4 className="ao5-hand">II. Begründetheit</h4><div className="ao6-mnemonic"><span>RRAG</span></div><div className="ao3-card"><b>100.000 €</b><p>Quellenmarker auf S. 66 – ohne zusätzliche, nicht ausgewiesene Deutung übernommen.</p></div><div className="ao6-roadcard"><h4>Anfechtungsbeschränkung · § 351 Abs. 1 AO</h4><p><strong>Liegen alle Voraussetzungen vor:</strong> Prüfe für alles, was das FA gerade geändert hat, und alles, was der Stpfl. will, das Korrekturverfahren. Bilde für Fehler, die hiernach nicht mehr korrigierbar sind, den Anfechtungsrahmen wie bei § 177 AO (Ober-/Untergrenze; Quelle verweist AEAO § 177 Nr. 3).</p><p><strong>Fehlt eine der Voraussetzungen:</strong> § 351 Abs. 1 AO greift nach der Quellenkarte nicht; Anfechtung ist uneingeschränkt möglich.</p></div></div>}

function HandbuchReiter(){const top=[["§ 370 (1) Nr. 1",""],["§ 370 (1) Nr. 2",""],["§ 153 (1) / § 149 (1)","green"],["§ 370 (1)+(4)",""],["§ 164","green"],["AEAO § 235 · 4.1.2 / 4.1.3","pink"],["§ 370 (4)",""],["§ 378 (1) / § 369 (2)","green"],["AEAO 153 · 2.6 / 2.7","pink"],["§ 371","green"]];return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Amtliches AO-Handbuch · Registersystem der Quelle</h3><div className="ao6-book"><div className="ao6-cover"><span>BUNDESMINISTERIUM DER FINANZEN</span><strong>BMF</strong><small>Amtliches AO-Handbuch<br/>2025</small></div><div className="ao6-registers"><div className="ao6-tabrow">{top.map(([x,t],i)=><span key={i} className={`ao6-tab${t?` ao6-tab--${t}`:""}`}>{x}</span>)}</div><div className="ao6-tabrow"><span className="ao6-bracket">Obj. Tatbest.</span><span className="ao6-bracket">Subj. T.</span><span className="ao6-bracket">Selbstanz.</span></div><h4 className="ao5-hand">Seitlich eindeutig lesbare AO-Reiter</h4><div className="ao6-tabrow"><span className="ao6-tab">§ 166</span><span className="ao6-tab ao6-tab--yellow">§ 164</span><span className="ao6-tab ao6-tab--yellow">§§ 171–177</span><span className="ao6-tab">§ 219</span><span className="ao6-tab">weitere markierte Reiter der Quelle</span></div><div className="ao6-fgolist"><span>§ 35</span><span>§ 38</span><span>§§ 57, 58, 62</span><span>§ 63</span><span>§§ 40, 41</span><span>§ 44</span><span>§ 40(2)</span><span>§ 47 / § 54</span><span>§§ 64, 65</span><span>§ 52d</span></div><p className="ao6-source-note">Unleserliche bzw. abgeschnittene Seitentabs der Seiten 72–74 werden nicht mit geratenen Normnummern aufgefüllt.</p></div></div></div>}

function Vollstreckung(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Vollstreckung</h3><div className="ao6-lanes"><section className="ao6-lane"><h4>Überprüfung allgemeine Vollstreckungsvoraussetzungen:</h4><div className="ao6-lane__track">{["§ 249 (1)","§ 251 (1)","§ 361","§ 254 (1)","§ 220","§ 259"].map(x=><span key={x} className="ao6-lawbox">{x}</span>)}</div></section><section className="ao6-lane"><h4>Überprüfung der jeweiligen Vollstreckungsmaßnahme:</h4><div className="ao6-lane__track">{["§ 281 (1)","§ 286","§ 263","§ 295","§ 286 (2)"].map(x=><span key={x} className="ao6-lawbox">{x}</span>)}</div></section></div><Note ton="green">Digitaler Nachbau des gedruckten Zwei-Pfeil-Schemas von PDF-S. 75.</Note></div>}

const fgo=[
["§ 33 FGO","Zulässigkeit des Finanzrechtswegs = gegen VA"],["§ 35 FGO","sachliche Zuständigkeit = FG"],["§ 38 FGO","örtliche Zuständigkeit = 18× FG in BRD"],["§§ 57, 62 FGO","Beteiligungsfähigkeit = Stpfl. selbst ohne Berater mögl."],["§ 58 FGO","Prozessfähigkeit"],["§ 63 FGO","Wen muss ich verklagen? → FA, das den VA erlassen hat; § 63(1) Nr. 1 FGO"],["§§ 40, 41 FGO","Auswahl der richtigen Klageart (muss Kläger nicht zwingend benennen) → i.d.R. Anfechtungsklage"],["§ 44 FGO","Erfolgloses Vorverfahren; Ausn.: Sprungklage § 45 FGO, Untätigkeit § 46 FGO"],["§ 40(2) FGO","Klagebefugnis (≙ § 350 AO)"],["§ 47 FGO / § 54 FGO","Klagefrist → grds. 1 Monat nach Bekanntgabe EE; Quelle ergänzt unten: FA ist auch Anbringungsbehörde (§ 47(2) FGO)"]
];
function FGOFahrtroute(){return <div className="ao3-sheet ao6-sheet"><h3 className="ao3-title">Zulässigkeits-/Sachurteilsvoraussetzungen · FGO-Fahrtroute</h3><div className="ao6-fgo-route">{fgo.map(([n,t],i)=><div className="ao6-fgo-step" key={n}><i>{i+1}</i><b>{n}</b><span>{t}</span></div>)}</div><Note>Die Quelle endet im sichtbaren PDF-Ausschnitt bei Station 10; darunter wird digital nichts ergänzt, was auf der Seite nicht belegt ist.</Note></div>}

export const AO6_SCHEMATA={
  "ao6-173-verschulden":Verschulden173,
  "ao6-173-rechtserheblichkeit":Rechtserheblichkeit173,
  "ao6-172":Schema172,
  "ao6-175-grundlagenbescheid":Grundlagen175,
  "ao6-175-rueckwirkend":Rueckwirkend175,
  "ao6-177-saldierung":Saldierung177,
  "ao6-fall-saldierung":FallSaldierung,
  "ao6-fall-einspruch-351":FallEinspruch351,
  "ao6-handbuch-reiter":HandbuchReiter,
  "ao6-vollstreckung":Vollstreckung,
  "ao6-fgo-fahrtroute":FGOFahrtroute,
};
export const ao6SchemaIds=Object.keys(AO6_SCHEMATA);
