import React from "react";
import "./ao-einheit3.css";
import "./ao-einheit5.css";
import "./ao-einheit6.css";
import "./ao-einheit8.css";

const Note=({children,ton="yellow"})=><div className={`ao5-note ao5-note--${ton}`}>{children}</div>;
const Arrow=()=> <span className="ao3-arrow">↓</span>;
const Step=({n,title,children,ton="blau"})=><div className={`ao8-step ao8-step--${ton}`}><i>{n}</i><div><b>{title}</b>{children}</div></div>;

function Objektiv370(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">① Objektiver Tatbestand · § 370 AO</h3><div className="ao8-stairs"><div className="ao8-devil">😈</div><div className="ao8-stair s1">1 · Tathandlung</div><div className="ao8-stair s2">2 · kausaler Taterfolg</div><div className="ao8-stair s3">3 · Vollendung</div><div className="ao8-stair s4">4 · Zeitpunkt</div><div className="ao8-stair s5">5 · Höhe</div></div><Step n="1" title="Tathandlung" ton="rot"><p><b>§ 370 Abs. 1 Nr. 1</b> oder <b>Nr. 2 AO</b>.</p></Step><Arrow/><Step n="2" title="Kausaler Taterfolg"><p>§ 370 Abs. 1 i.V.m. Abs. 4 S. 1/2 AO. Quellenbeispiele: <b>zu viel VorSt</b> · <b>zu niedriger F-Bescheid</b>.</p><p className="ao8-cross">Nicht: Steuer lediglich nicht bezahlt.</p></Step><Arrow/><Step n="3" title="Vollendung"><p>§ 370 Abs. 4 S. 1 HS 2 AO.</p></Step><Arrow/><Step n="4" title="Zeitpunkt des Taterfolgs" ton="violett"><p>Quellenverweise über AEAO / § 235; Zeitpunkt gesondert festhalten.</p></Step><Arrow/><Step n="5" title="Höhe des Taterfolgs" ton="gruen"><p>§ 370 Abs. 4 S. 3 AO + grün markierte Quellenverweise.</p></Step></div>}
function Subjektiv370(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">② Subjektiver Tatbestand</h3><div className="ao8-levels"><div className="ao8-level ao8-level--red"><b>Vorsatz!</b><span>§ 369 Abs. 2 AO → § 15 StGB</span><strong>Wissen &amp; Wollen · „bewusst?“</strong><small>AEAO zu § 153 Nr. 2.6</small></div><div className="ao8-level ao8-level--yellow"><b>Leichtfertig</b><span>§ 378 Abs. 1 AO</span><strong>keine StHi · Ordnungswidrigkeit</strong></div><div className="ao8-level ao8-level--grey"><b>fahrlässig</b><span>Vorsehen / Versehen</span></div></div></div>}
function Folgen370(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">③ Rechtswidrigkeit &amp; Schuld · Rechtsfolgen</h3><Note ton="pink"><b>Bei StHi nach Quellenkarte: „immer erfüllt!“</b></Note><div className="ao8-devil-card"><span>😈</span><div><b>Steuerhinterziehung</b><strong>Festsetzungsfrist 10 Jahre</strong><p>§ 169 Abs. 2 S. 2 AO</p></div></div><div className="ao8-folge-grid"><div><b>Zinsen</b><p>§ 235 AO / § 238 AO – Quellenblock separat prüfen.</p></div><div><b>SteuFa</b><p>Ermittlungs-/Folgeschiene der Quelle.</p></div><div><b>Selbstanzeige</b><p>§ 371 AO → eigener Prüfblock.</p></div><div><b>Korrektur</b><p>Quellenhinweis: keine Sperre nach § 173 Abs. 2 AO.</p></div></div></div>}
function Selbstanzeige371(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">Selbstanzeige · § 371 AO</h3><div className="ao8-sa-head">vollständig berichtigen · ergänzen · nachholen</div><Step n="1" title="Vollständigkeit" ton="gruen"><p>Zu allen unverjährten Steuerstraftaten <b>einer Steuerart</b> in dem von § 371 Abs. 1 AO verlangten Umfang.</p></Step><Arrow/><Step n="2" title="Sperrgründe § 371 Abs. 2 AO" ton="rot"><ul><li>Bekanntgabe / Erscheinen zur steuerlichen Prüfung oder Einleitung Straf-/Bußgeldverfahren</li><li>Tat bereits entdeckt und Täter wusste oder musste damit rechnen</li><li>verkürzte Steuer / nicht gerechtfertigter Vorteil <b>über 25.000 € je Tat</b></li><li>besonders schwerer Fall nach § 370 Abs. 3 S. 2 Nr. 2–6</li></ul></Step><Arrow/><Step n="3" title="weitere Anforderungen"><p>Berichtigung/Ergänzung/Nachholung und Zahlungsanforderungen der markierten Absätze prüfen.</p></Step><div className="ao8-sa-result"><div className="ok">✓ wirksame Selbstanzeige</div><div className="no">✕ keine wirksame Selbstanzeige = strafbare StHi</div></div><Note>Daneben: <b>§ 378 Abs. 3 AO</b> für die leichtfertige Steuerverkürzung; <b>§ 398a AO</b> als weiterer Quellenhinweis.</Note></div>}
function HaftungFahrtroute(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">Haftung · „Einstehenmüssen für eine fremde Schuld“</h3><div className="ao8-foreign">fremde Schuld</div><Step n="1" title="Auslegung der Einwendungen"><p>Im äußeren Fall möglichst alle Angriffe gegen Haftungsbescheid / Zahlungsaufforderung erfassen.</p></Step><Arrow/><Step n="2" title="Einspruch"><p>Zulässigkeit und Begründetheit gegen den Haftungsbescheid prüfen.</p></Step><Arrow/><Step n="3" title="Haftungstatbestand"><p>Besondere Norm aus <b>§§ 69–76 AO</b> wählen.</p></Step><Arrow/><Step n="4" title="Haftungsbescheid / Zahlungsaufforderung"><p>§ 191 AO und die Quellenfolge bis zur Inanspruchnahme abarbeiten.</p></Step><div className="ao8-mini-route"><span>Haftungsschuld</span><b>→</b><span>Haftungsbescheid</span><b>→</b><span>Zahlungsaufforderung</span></div></div>}
function Vertreter69(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">I. Haftung des Vertreters · § 69 AO</h3><Step n="1" title="Person i.S.d. § 34 AO"><p>insbesondere GmbH-GF · § 35 Abs. 1 GmbHG</p></Step><Arrow/><Step n="2" title="Anspruch nach § 37 AO"><p>Steueranspruch gegen die GmbH.</p></Step><Arrow/><Step n="3" title="schuldhafte Pflichtverletzung"><ul><li>fristgerechte Abgabe StErkl./StAnm.</li><li>nach bestem Wissen &amp; Gewissen</li><li>pünktliche Zahlung fälliger Steuern</li></ul><Note ton="green">Bei Zahlungsschwierigkeiten: Quelle verlangt <b>quotale Tilgung</b>; Lohnsteuer als gesonderter Warnhinweis.</Note></Step><Arrow/><Step n="4" title="Verschulden"><p>Vorsatz oder grobe Fahrlässigkeit; bei GmbH-GF laut Quelle regelmäßig besonders streng.</p></Step><Arrow/><Step n="5" title="kausaler Schaden" ton="rot"><p><b>was die GmbH hätte zahlen können</b> − <b>was der GF gezahlt hat</b> = Haftungsschaden</p></Step><table className="ao8-table"><thead><tr><th>Quellenbeispiel</th><th>Betrag</th></tr></thead><tbody><tr><td>GmbH hat</td><td>100.000 €</td></tr><tr><td>Verbindlichkeiten</td><td>100.000 €</td></tr><tr><td>fällige Steuern</td><td>20.000 €</td></tr></tbody></table></div>}
function MehrereGF(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">Sonderfall § 69 AO · mehrere Geschäftsführer</h3><div className="ao8-gf"><div className="ao8-person"><span>🙂</span><b>A</b><small>Bereich A</small></div><div className="ao8-divider">schriftl. Vereinbarung</div><div className="ao8-person"><span>🙂</span><b>B</b><small>Bereich B</small></div></div><ol className="ao8-rules"><li><b>Grundsatz:</b> Gesamtverantwortung aller GF.</li><li><b>Ausnahme:</b> schriftliche interne Ressortvereinbarung; A und B übernehmen abgegrenzte Bereiche.</li><li><b>Rückausnahme:</b> Überwachungspflichten bleiben, wenn Pflichtverstöße erkennbar werden / Anlass zur Kontrolle besteht.</li></ol></div>}
function Haftung71(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">II. Haftung des Steuerhinterziehers · § 71 AO</h3><div className="ao8-71"><span className="ao8-devil-big">😈</span><div><b>begangene Steuerhinterziehung</b><strong>zum fremden Vorteil</strong><small>Prüfe § 370 AO</small></div></div><Arrow/><Step n="2" title="kausaler Schaden"><p>Schaden aus der Steuerhinterziehung bestimmen.</p></Step><Arrow/><div className="ao8-folge-grid"><div><b>Haftung</b><p>persönlich / unbeschränkt nach Quellenhinweis.</p></div><div><b>Bescheid</b><p>§ 191 AO · Ermessensentscheidung.</p></div></div><Note>Haftungsschuld und steuerstrafrechtliche Sanktion bleiben getrennte Ebenen.</Note></div>}
function Haftung74(){return <div className="ao3-sheet ao8-sheet"><h3 className="ao3-title">III. Haftung des Eigentümers von Gegenständen · § 74 AO</h3><div className="ao8-factory"><div className="ao8-owner"><span>🙂</span><b>C</b></div><div className="ao8-building">🏭<small>Fabrik / Gegenstand</small></div><div className="ao8-rent">Vermietung / Überlassung → Gesellschaft</div></div><Step n="1" title="Gegenstand dient dem Unternehmen"><p>Unternehmensdienlichkeit nach dem §-74-Quellenblock.</p></Step><Arrow/><Step n="2" title="Eigentum / wesentliche Beteiligung"><p>Die Quelle markiert das Eigentümer-/Beteiligungsverhältnis ausdrücklich in der Skizze.</p></Step><Arrow/><Step n="3" title="Haftungsbescheid"><p>§ 191 AO anschließen; Haftungsumfang nur innerhalb des § 74 AO.</p></Step></div>}

export const AO8_SCHEMATA={
"ao8-370-objektiv":Objektiv370,
"ao8-370-subjektiv":Subjektiv370,
"ao8-370-folgen":Folgen370,
"ao8-371-selbstanzeige":Selbstanzeige371,
"ao8-haftung-fahrtroute":HaftungFahrtroute,
"ao8-69-vertreterhaftung":Vertreter69,
"ao8-mehrere-gf":MehrereGF,
"ao8-71-sth-haftung":Haftung71,
"ao8-74-eigentuemerhaftung":Haftung74,
};
export const ao8SchemaIds=Object.keys(AO8_SCHEMATA);
export default AO8_SCHEMATA;
