import React from "react";
import "./ao-einheit3.css";
import "./ao-einheit5.css";

const Box=({children,ton="blau",className=""})=><div className={`ao3-box ao3-box--${ton} ${className}`}>{children}</div>;
const Arrow=()=> <span className="ao3-arrow">↓</span>;
const Note=({children,ton="yellow"})=><div className={`ao5-note ao5-note--${ton}`}>{children}</div>;
const Tabs=({items})=><div className="ao5-tabs">{items.map(([x,t],i)=><span key={i} className={t}>{x}</span>)}</div>;
const Timeline=({points})=><div className="ao5-timeline" style={{"--n":points.length}}>{points.map(([d,l,t],i)=><div key={`${d}-${i}`} className={`ao5-point${t?` ao5-point--${t}`:""}`}><b>{d}</b><small>{l}</small></div>)}</div>;
const Step=({n,children})=><div className="ao5-step"><i>{n}</i><div>{children}</div></div>;

function VDNGrundlagen(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">Korrekturvorschriften · § 164 AO · VdN = Generalschlüssel</h3><div className="ao5-key"><div className="ao5-key__icon">⚿</div><div className="ao5-key__box">VdN hält alles offen<br/><small>solange wirksam</small></div></div><div className="ao5-flow"><Box ton="gruen"><b>Sinn & Zweck</b><small>Steuer schon festsetzen, obwohl Fall noch gar nicht geprüft</small></Box><span>→</span><Box ton="blau"><b>Wirkung</b><small>punktuelle Änderung ↑ / ↓ nach § 164 Abs. 2 AO</small></Box></div><div className="ao5-grid4"><section><h4>BP-Fall</h4><p>typischer Einsatz vor/bei Betriebsprüfung</p></section><section><h4>Schätzung</h4><p>§ 162 AO</p></section><section><h4>Kombination</h4><p>Quelle nennt §§ 83 / 87</p></section><section><h4>Steueranmeldungen</h4><p>gesetzliche VdN-Systematik</p></section></div><Note><b>Quelle S. 3–5:</b> keine Begründung erforderlich; für eine rechtmäßige Prüfungsanordnung ist ein VdN nicht nötig (AEAO § 193 Nr. 1).</Note><Tabs items={[["§ 164(1)","green"],["§ 164(2)","green"],["§ 162","yellow"],["AEAO § 193","pink"]]}/></div>}

function VDNArtenDauer(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">Woher VdN? · Arten und Lebensdauer</h3><div className="ao5-grid3"><section><h4>a) ausdrücklicher Vermerk</h4><p>im Bescheid; Quelle verweist auf unselbständige Nebenbestimmung / § 120 AO</p><b className="ao5-hand">Mehrweg-VdN</b><p>kein VdN bei „endgültig“ / „ohne Nebenbest.“</p></section><section><h4>b) kraft Gesetzes</h4><p>automatisch</p><b className="ao5-hand">Einweg-VdN → USt-JE · § 168 AO</b><p className="ao5-hand" style={{color:"var(--r)"}}>„Unzerstörbarer-VdN“ → USt-VA · § 164 Abs. 1 S. 2 AO</p></section><section><h4>c) über § 129 AO</h4><p>VdN vom FA gewollt, aber wegen mechanischen Versehens nicht aufgenommen; vorherige §-129-Berichtigung laut Quelle nicht nötig.</p><b className="ao5-hand">Mehrweg-VdN direkt nutzbar</b></section></div><Note ton="green"><b>Wie lange?</b> Innerhalb der regulären 4-jährigen Festsetzungsfrist; Mehrweg-VdN grundsätzlich bis zur ausdrücklichen Aufhebung. Quelle markiert die Aufhebung schriftlich und verweist auf § 164 Abs. 3 S. 2 AO.</Note><Timeline points={[["8.8.02","EStB 01 · VdN"],["8.8.03","Änderung nach § 164(2) · VdN bleibt"],["9.9.04","Änderung / Aufhebung VdN","pink"],["Einspruch","unbegründet, da VdN noch da? – Quellenzeitstrahl","pink"],["reg. FF","reguläres Fristende"]]}/><div className="ao5-grid2"><section><h4>Einweg-VdN USt</h4><p>fällt nach der Quelle weg, wenn der erste USt-Jahresbescheid nicht wiederum zum Mehrweg-VdN befördert wird.</p></section><section><h4>Nach Ablauf reg. FF</h4><p>Mehrweg / Einweg / „unzerstörbarer“ VdN entfallen nach § 164 Abs. 4 S. 1 AO.</p><p><b>Ausnahme:</b> Ablaufhemmungen § 171 Abs. 3, 3a, 4 AO können VdN über das reguläre Ende hinaus aufrechterhalten.</p></section></div><Tabs items={[["§ 164(1)","green"],["§ 168","green"],["§ 164(2)","green"],["§ 164(3)","green"],["§ 164(4)","green"],["§ 171(3)/(3a)/(4)","pink"]]}/></div>}

function VorlaeufigGrundlagen(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">§ 165 AO · Vorläufige Festsetzung = Skalpell</h3><div className="ao5-flow"><Box ton="blau"><b>Fall grundsätzlich geprüft</b><small>aber punktuelle Ungewissheit bleibt</small></Box><span>→</span><Box ton="gruen"><b>nur punktuell offen</b><small>Änderung ↑ / ↓ innerhalb des Vorläufigkeitsumfangs</small></Box></div><div className="ao5-key"><div className="ao5-key__icon">✂</div><div className="ao5-key__box">VdN = Generalschlüssel<br/><span style={{color:"var(--g)"}}>§ 165 = Skalpell</span></div></div><Note><b>Wirkung:</b> Fall nur punktuell änderbar; Umfang & Grund sind nach der Quelle anzugeben. Die Vorläufigkeit umfasst auch die nachgelagerte Frage nach der Höhe der betroffenen Einkünfte.</Note><div className="ao5-grid2"><section><h4>① § 165 Abs. 1 S. 1 AO</h4><b>Sachverhaltsungewissheit</b><ul><li>Liebhaberei</li><li>ungewisse Erbschaft</li><li>15%-Grenze / Quellenbeispiel</li></ul></section><section><h4>② § 165 Abs. 1 S. 2 AO</h4><b>ungewisse Rechtslage</b><p>wegen anhängigem Verfahren bei BFH / BVerfG, soweit für den Stpfl. bedeutsam</p></section></div><div className="ao3-card"><b>VORLÄUFIGE FESTSETZUNG</b><p>Digitale Merkkarte nach PDF-S. 16: punktuelle Unsicherheit wird „operiert“, der restliche Bescheid bleibt unberührt.</p></div><Tabs items={[["§ 165(1) S.1","yellow"],["§ 165(1) S.2","yellow"],["§ 165(2)","green"]]}/></div>}

function VorlaeufigDauer(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">§ 165 AO · Woher? Wie lange? Ablaufhemmung</h3><div className="ao5-grid2"><section><h4>Woher § 165?</h4><ul><li>ausdrücklicher Vermerk im Bescheid → Quelle verweist auf § 120 AO</li><li>kein § 165 bei „endgültig“ / „ohne Nebenbest.“</li><li>Quelle verweist daneben auf § 129 AO wie beim VdN</li></ul><b className="ao5-hand">immer Mehrweg</b></section><section><h4>Wie lange?</h4><p>bis zur ausdrücklichen Aufhebung nach § 165 Abs. 2 S. 2 AO</p><b className="ao5-hand">„für endgültig erklärt“</b></section></div><div className="ao5-sourcebox"><b>Änderungs-EStB #2 nach EStB #1 mit 3 Vorläufigkeiten</b><div className="ao5-grid2"><section><h4>a) keine Aussage zu § 165</h4><p>→ alle Vorläufigkeiten nach der Quellennotiz noch da</p></section><section><h4>b) „Vorläufig weiterhin bzgl. BFH Az.: II R 14/19“</h4><p>→ Umfang aller Vorläufigkeiten neu bestimmt; die zwei anderen sind weg.</p></section></div></div><h4 className="ao5-hand">Eigene Ablaufhemmung · § 171 Abs. 8 AO</h4><div className="ao5-flow"><Box ton="gelb"><b>① Beseitigung Ungewissheit</b><small>bei Quellenfall § 165(1) S.2 Nr.4: ab BStBl I</small></Box><span>+</span><Box ton="pink"><b>② aktive Kenntnis FA</b></Box><span>→</span><Box ton="gruen"><b>Nachlauf</b><small>+1 Jahr bei § 165(1) S.1 · +2 Jahre bei § 165(1) S.2</small></Box></div><Tabs items={[["§ 165(2) S.1","green"],["§ 165(2) S.2","green"],["§ 171(8) S.1","pink"],["§ 171(8) S.2","pink"]]}/></div>}

const baseRows=[["Schreib-/Rechenfehler","§ 171 Abs. 2 S. 1 AO","§ 129 AO"],["Schreib-/Rechenfehler Stpfl.","§ 171 Abs. 2 S. 2 AO","§ 173a AO"],["Antrag vor Ablauf FF","§ 171 Abs. 3 AO","§ 164 Abs. 2 / § 173 Abs. 1 / …"],["zulässiger Einspruch","§ 171 Abs. 3a AO","§ 367 Abs. 2 S. 1 AO"],["AP + wirks. PA","§ 171 Abs. 4 AO","§ 164(2) / § 173(1) / …"],["SteuFa / StraBuSt","§ 171 Abs. 5 AO","? ______ und § 173(1) · nicht: ?"],["StHi","§ 169 Abs. 2 S. 2 AO","? ______ und § 173(1) · nicht: ?"],["Beichte","§ 171 Abs. 9 AO","§ 173(1) AO · nicht: ?"],["wirks. F-Bescheid","§ 171 Abs. 10 S. 1 AO","§ 175 Abs. 1 Nr. 1 AO"],["Annahme Erbe","§ 171 Abs. 12 AO","§ 173 Abs. 1 AO"],["Erstattung","§ 171 Abs. 14 AO","— (ESt-Bescheid)"],["Vorläufige Festsetzung","§ 171 Abs. 8 S. 1 AO","§ 165 Abs. 2 S. 1 AO"],["Vorläufige Festsetzung","§ 171 Abs. 8 S. 2 AO","§ 165 Abs. 2 S. 2 AO"]];
function Pairs({rows=baseRows}){return <div className="ao5-pairs"><section><b>Ereignis</b><b>Frist-/Hemmungsnorm</b><b>♥</b><b>Korrektur / Folge</b></section>{rows.map(([a,b,d],i)=><section key={i}><span>{a}</span><span>{b}</span><b className="ao5-heart">{d.startsWith("—")?"–":"♥"}</b><span>{d}</span></section>)}</div>}
function Korrekturpaerchen(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">Korrekturpärchen · Erweiterung um vorläufige Festsetzung</h3><Pairs/><Note>Neu auf PDF-S. 21: <b>§ 171 Abs. 8 S. 1 AO ♥ § 165 Abs. 2 S. 1 AO</b> und <b>§ 171 Abs. 8 S. 2 AO ♥ § 165 Abs. 2 S. 2 AO</b>. Die offenen Fragezeichen aus den älteren Zeilen bleiben offen.</Note></div>}

function FBescheid(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">🧪 Wirksamkeitsformel F-Bescheide · VA mit Bindungswirkung</h3><div className="ao5-formula"><div><i>1</i><b><span style={{color:"var(--g)"}}>nicht</span> <span style={{color:"var(--r)"}}>NICHTIG ☠</span></b></div><div><i>2</i><b>ordnungsgemäße Bekanntgabe → insb. F-Bescheide · § 182 Abs. 1 S. 1 AO</b></div><div><i>3</i><b>ohne Wirkhinweis <u>oder</u> mit Wirkhinweis und FF-ESt/Folgebescheid läuft noch</b></div></div><div className="ao5-result">= wirksam</div><div className="ao5-flow"><Box ton="gruen"><b>wirksamer Grundlagenbescheid</b></Box><span>→</span><Box ton="blau"><b>Bindungswirkung für Folgebescheid</b><small>§ 182 Abs. 1 S. 1 AO</small></Box></div><Note>PDF-S. 23 setzt vor die Formel ausdrücklich: „eines wirksamen Grundlagenbescheids (Standard-Fehler egal!)“ bei § 171 Abs. 10 S. 1 AO.</Note></div>}

function Offenbare129(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">§ 129 AO · Berichtigung offenbarer Unrichtigkeit</h3><div className="ao5-headless"><div className="ao5-headless__figure"><span>♙</span>„kopfloser“ Finanzbeamter</div><div className="ao5-sourcebox"><b>① offenbare Unrichtigkeit</b><ul><li>Schreibfehler (z.B. 3.000 € statt zutreffend 300 €)</li><li>Rechenfehler (z.B. 800 € + 300 € = 500 €)</li><li>ähnlicher Fehler: mechanisch / versehentlich</li><li>typischer unbewusster Flüchtigkeitsfehler</li><li>das Gemachte weicht von dem ab, was der FA-Bearbeiter bei Bewusstsein gewollt hätte</li><li><b>Rechts- und Denkfehler müssen ausgeschlossen sein</b></li><li>Fehler für jeden Dritten erkennbar aus StErkl. + Anlagen + Akte + Bescheid</li></ul></div></div><div className="ao5-sourcebox" style={{marginTop:12}}><b>② beim Erlass eines VA</b><p>Grundsatz: nur eigener Fehler des FA.</p><p><b>Ausnahme der Quelle – Übernahmefehler:</b> Stpfl. begeht unbewusst einen §-129-Fehler, der für das FA aus Erklärung + Anlagen erkennbar war, aber trotz Überprüfung (insb. „RMS-Prüfhinweis“) nicht erkannt und übernommen wurde.</p></div><div className="ao5-rf"><div className="up"><strong>§ 129 S. 1 AO</strong><p>Punktuelle Berichtigung möglich ↑ · Ermessen („darf“; Quelle verweist auf § 5 AO)</p></div><div className="down"><strong>§ 129 S. 2 AO</strong><p>Punktuelle Berichtigung zwingend ↓</p></div></div><Note ton="green">Ablaufhemmung: <b>§ 171 Abs. 2 S. 1 AO ♥</b></Note><Tabs items={[["§ 129 S.1","green"],["§ 129 S.2","green"],["§ 171(2) S.1","pink"]]}/></div>}

function Fehler173a(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">§ 173a AO · Schreib-/Rechenfehler des Stpfl. / Beraters</h3><Box ton="gruen"><b>① Schreib-/Rechenfehler des Stpfl. ↔ Berater</b><small>z.B. 1.200 € statt 2.100 €; 400 € + 100 € = 600 €</small></Box><Note ton="red"><b>Nicht:</b> versehentlich nichts eingetragen.</Note><div className="ao5-flow"><Box ton="blau"><b>Aufstellung mit eingereicht?</b></Box><span>→</span><Box ton="gelb"><b>§ 129 AO?</b><small>Übernahmefehler (mechanisches Versehen)</small></Box></div><div className="ao5-flow"><Box ton="blau"><b>Aufstellung nicht mit eingereicht?</b></Box><span>→</span><Box ton="pink"><b>§ 173 AO?</b><small>neue Tatsache</small></Box></div><div className="ao5-grid2"><section><h4>② bei Erstellung StErkl.</h4><p>inkl. Excel-Tabellen usw.</p></section><section><h4>③ kausale Tatsachen</h4><p>z.B. Höhe der Spenden unzutreffend mitgeteilt → gesondert prüfen</p></section></div><div className="ao5-rf"><div className="up"><strong>Rechtsfolge</strong><p>punktuelle Änderung ↑ / ↓</p></div><div className="down"><strong>Ablaufhemmung</strong><p>§ 171 Abs. 2 S. 2 AO ♥</p></div></div><div className="ao3-card"><b>Schreib-/Rechenfehler StErkl.</b><p>Digitale Merkkarte nach PDF-S. 33.</p></div></div>}

function NeueTatsachen173(){const left=["Tatsache","dem FA nachträglich bekannt","Steuer ↑","kein Ermittlungsfehler FA","Rechtserheblichkeit","keine Sperre § 173 Abs. 2 AO"],right=["Tatsache","dem FA nachträglich bekannt","Steuer ↓","kein grobes Verschulden Stpfl./StB","Rechtserheblichkeit","keine Sperre § 173 Abs. 2 AO"];return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">§ 173 AO · Neue Tatsachen</h3><div className="ao5-compare"><section><h4>§ 173 Abs. 1 Nr. 1 AO ↑</h4><div className="ao5-steps">{left.map((x,i)=><Step key={x} n={i+1}>{x}</Step>)}</div></section><section><h4>§ 173 Abs. 1 Nr. 2 AO ↓</h4><div className="ao5-steps">{right.map((x,i)=><Step key={x} n={i+1}>{x}</Step>)}</div></section></div><div className="ao5-branch-result">↘ Rechtsfolge ↙<br/>Aufhebung <u>oder</u> punktuelle Änderung</div><div className="ao5-grid2"><section><h4>① Tatsache · AEAO § 173 Nr. 1, 6.2 + 6.3</h4><p>Lebenssachverhalt: was in Wirklichkeit passiert oder wider Erwarten nicht passiert ist.</p><p><b>Nicht:</b> bloße steuerliche Würdigung, z.B. als „BE“ / „BA“.</p><p><b>Spinnenregel:</b> grundsätzlich jede Tatsache separat prüfen; Ausnahme Quelle: komplett neue Einkunftsquelle = 1 Tatsache inkl. Saldo.</p></section><section><h4>② nachträgliches Bekanntwerden · AEAO § 173 Nr. 1.3 + 2</h4><p>Tatsache muss vor Bescheid existiert haben.</p><p>Alles aus StErkl. + Anlagen + Akte gilt als bekannt.</p><p>Nachträglich = Kenntnis erst, nachdem der zuständige SB den Bescheid, der geändert werden soll, freigegeben hat.</p><p>Bescheide, die nur nach § 175 Abs. 1 Nr. 1 oder vollautomatisiert nach § 165 Abs. 2 geändert wurden, zählen laut Quelle dabei nicht mit.</p></section></div><div className="ao5-grid3"><section><h4>③ steuerliche Auswirkung ↑ / ↓</h4><p>kurze steuerliche Würdigung; Vergleich Steuer vorher ↔ nachher · AEAO § 173 Nr. 1.4</p></section><section><h4>④ Nr. 1: kein Ermittlungsfehler FA</h4><p>AEAO § 173 Nr. 4; nur relevant bei vollständiger Erklärung nach bestem Wissen/Gewissen und offensichtlichem Prüfhinweis, dem das FA nicht nachging.</p></section><section><h4>④ Nr. 2: kein grobes Verschulden Stpfl./StB</h4><p>eigene Verschuldensprüfung für die steuermindernde Richtung.</p></section></div><div className="ao3-card"><b>NEUE TATSACHEN</b><p>Digitale Merkkarte nach PDF-S. 38: zwei Richtungen – Nr. 1 ↑ und Nr. 2 ↓.</p></div><Tabs items={[["§ 179(3)","green"],["§ 164","yellow"],["§ 165","yellow"],["§ 169/170","green"],["§ 164(2)","yellow"],["§ 171(3)/(3a)/(4)","green"],["§ 165(2)","yellow"],["§ 171(8)","green"],["§ 173","pink"]]}/></div>}

function Fall6(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">Fall 6 · Miete Januar 2023 am 30.12.2022 gezahlt</h3><div className="ao5-fallbox"><h4>Erklärung 2022</h4><table className="ao5-money"><tbody><tr><td>Miete Januar bis Dezember 2022</td><td>24.000 €</td></tr><tr><td>Miete Januar 2023, fällig 01.01.2023, gezahlt 30.12.2022</td><td>2.000 €</td></tr><tr><td>Summe</td><td>26.000 €</td></tr></tbody></table><p>Die Mieteinnahmen wurden erklärungsgemäß berücksichtigt. Später erkennt der zuständige Sachbearbeiter, dass die Januar-Miete 2023 zu den Einnahmen des Jahres 2023 gehört.</p><div className="ao5-source-answer">Neue Tatsache i.S.d. § 173 AO? → Nein, da die Tatsache „Zahlung 30.12.2022“ bekannt war.</div></div><Note>Quelle trennt Tatsache und rechtliche Würdigung: Die Zahlung war bekannt; nur die zeitliche steuerliche Einordnung wird später anders gesehen.</Note></div>}
function Fall7(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">Fall 7 · Zweifamilienhaus und Wohnflächen</h3><div className="ao5-fallbox"><p>Stpfl. erwirbt ein Zweifamilienhaus, bewohnt eine Wohnung selbst und vermietet die zweite. Aufgrund der erklärten Wohnflächen berücksichtigt das FA <b>40 %</b> der Schuldzinsen als Werbungskosten.</p><div className="ao5-flow"><Box ton="blau"><b>eigengenutzt</b><small>100 m²</small></Box><span>↔</span><Box ton="gruen"><b>vermietet</b><small>50 m²</small></Box></div><div className="ao5-source-answer">Liegt eine (neue) Tatsache i.S.d. § 173 AO vor? → Ja! Nr. 1</div></div></div>}
function Fall8(){return <div className="ao3-sheet ao5-sheet"><h3 className="ao3-title">Fall 8 · neue vermietete Wohnung</h3><div className="ao5-fallbox"><p>Der Stpfl. erzielt seit Jahren Vermietungseinkünfte aus mehreren Mietobjekten. 2022 erwirbt und vermietet er eine weitere Wohnung, erklärt diese aber versehentlich nicht.</p><div className="ao5-calc"><div><b>Einnahmen neue Wohnung</b><span>12.000 €</span></div><div><b>Ausgaben neue Wohnung</b><span>21.500 €</span></div><div><b>Saldo</b><span>-9.500 €</span></div></div><div className="ao5-source-answer">Quellennotiz: „1 Tatsache inkl. -9.500 € → Nr. 2“</div></div><Note>Spinnenregel-Ausnahme der Quelle: komplett neue Einkunftsquelle als eine Tatsache inklusive Saldo behandeln.</Note></div>}

export const AO5_SCHEMATA={"ao5-vdn-grundlagen":VDNGrundlagen,"ao5-vdn-arten-dauer":VDNArtenDauer,"ao5-vorlaeufig-grundlagen":VorlaeufigGrundlagen,"ao5-vorlaeufig-dauer":VorlaeufigDauer,"ao5-korrekturpaerchen":Korrekturpaerchen,"ao5-fbescheid-wirksamkeit":FBescheid,"ao5-129":Offenbare129,"ao5-173a":Fehler173a,"ao5-173":NeueTatsachen173,"ao5-fall6":Fall6,"ao5-fall7":Fall7,"ao5-fall8":Fall8};
export const ao5SchemaIds=Object.keys(AO5_SCHEMATA);
