import React from"react";
import K1ErbStPruefschemaV2 from"./K1ErbStPruefschemaV2";
import K1ErbStSchemaAlleV3 from"./K1ErbStSchemaAlleV3";
import"./erbst2f.css";import"./erbst3.css";
const E2=[
["erbst2f-schema-nnas","NNAS: Nettowerte → Aufteilung → Schuldenbegrenzung","erbst2f-nnas","Einheit 2 · PDF-S. 151–176"],["erbst2f-schema-kosten","Erbfallkosten vs. Erwerbsnebenkosten","erbst2f-kosten","Einheit 2 · PDF-S. 177–198"],["erbst2f-schema-fall15","Fall 15: Gesamtfall WSV → NNAS → E","erbst2f-fall15","Einheit 2 · PDF-S. 199–237"],["erbst2f-schema-bewg-master","§ 12 ErbStG als Türöffner ins BewG","erbst2f-bewg-master","Einheit 2 · PDF-S. 238–271"],["erbst2f-schema-gemeiner-wert","§ 9 BewG: gemeiner Wert / Auffangtatbestand","erbst2f-gemeiner-wert","Einheit 2 · PDF-S. 272–281"],["erbst2f-schema-bedingungen","§§ 4–8 BewG: Bedingungen und Befristungen","erbst2f-bedingungen","Einheit 2 · PDF-S. 282–302"],["erbst2f-schema-wertpapiere","§ 11 BewG: Wertpapiere und Anteile","erbst2f-wertpapiere","Einheit 2 · PDF-S. 303–324"],["erbst2f-schema-forderungen","§ 12 BewG: Forderungen und Schulden","erbst2f-forderungen","Einheit 2 · PDF-S. 325–362"],["erbst2f-schema-darlehen","§ 12 BewG: Fälligkeits- vs. Tilgungsdarlehen","erbst2f-darlehen-tabelle","Einheit 2 · PDF-S. 363–393"],["erbst2f-schema-fall16","Fall 16: Fälligkeitsdarlehen / Tabelle 1","erbst2f-fall16","Einheit 2 · PDF-S. 394–408"],["erbst2f-schema-fall17","Fall 17: Tilgungsdarlehen / Tabelle 2","erbst2f-fall17","Einheit 2 · PDF-S. 409–423"],["erbst2f-schema-fall18","Fall 18: niedrig verzinste Forderung","erbst2f-fall18","Einheit 2 · PDF-S. 424–443"],["erbst2f-schema-flags","Fähnchenkleben: Gesamtfahrtroute ErbStG ↔ BewG","erbst2f-flags","Einheit 2 · PDF-S. 444–457"]];
const E3=[
["erbst3-schema-kapitalforderung","§ 12 BewG: Darlehen / Zins-Sonderfälle","erbst3-kapitalforderung","Einheit 3 · PDF-S. 1–6"],["erbst3-schema-stille","Typisch stille Beteiligung / partiarisches Darlehen","erbst3-stille","Einheit 3 · PDF-S. 7–35"],["erbst3-schema-nutzungen","Nutzungen & Leistungen: Jahreswert × Vervielfältiger","erbst3-nutzungen","Einheit 3 · PDF-S. 36–68"],["erbst3-schema-jahreswert","§§ 15/16 BewG: Jahreswert und Begrenzung","erbst3-jahreswert","Einheit 3 · PDF-S. 36–68"],["erbst3-schema-vervielfaeltiger","§§ 13/14 BewG: Vervielfältiger","erbst3-vervielfaeltiger","Einheit 3 · PDF-S. 69–89 / 145–163"],["erbst3-schema-leibrente-sonder","Mindest-/Höchstdauer und mehrere Berechtigte","erbst3-leibrente-sonder","Einheit 3 · PDF-S. 101–159"],["erbst3-schema-grundstueck-einstieg","Grundstück: § 12 Abs. 3 ErbStG → §§ 151/157 BewG","erbst3-grundstueck-einstieg","Einheit 3 · PDF-S. 164–200"],["erbst3-schema-grundvermoegen","§ 176 BewG: Umfang des Grundvermögens","erbst3-grundvermoegen","Einheit 3 · PDF-S. 201–221"],["erbst3-schema-nachweis","§ 177 / § 198: niedrigerer gemeiner Wert","erbst3-nachweis","Einheit 3 · PDF-S. 222–246"],["erbst3-schema-bewertungsuebersicht","Grundbesitz: Methodenübersicht","erbst3-bewertungsuebersicht","Einheit 3 · PDF-S. 247–280"],["erbst3-schema-unbebaut","§§ 178/179: unbebautes Grundstück","erbst3-unbebaut","Einheit 3 · PDF-S. 281–317"],["erbst3-schema-bebaut","§ 181 → § 182: Grundstücksart vor Verfahren","erbst3-bebaut","Einheit 3 · PDF-S. 318–355"],["erbst3-schema-ertragswert","§§ 184–188: Ertragswert-Masterschema","erbst3-ertragswert","Einheit 3 · PDF-S. 356–380"],["erbst3-schema-fall27","Fall 27: vollständige Ertragswertrechnung","erbst3-fall27","Einheit 3 · PDF-S. 381–448"]];
function Stack({titel,lead,bloecke}){return <><section className="abschnitt"><div className="pagehead"><div><span className="kicker">Klausur 1 · Erbschaftsteuer · Prüfschema</span><h1>{titel}</h1><p className="lead">{lead}</p></div><span className="zaehler">{bloecke.length} Schemata</span></div></section><div className="erbst3-schema-stack">{bloecke.map(([id,t,s,q])=><section className="abschnitt ao-schema-section" id={id} key={id}><div className="kst-abschnitt-kopf"><div><span className="kicker">{q}</span><h2>{t}</h2></div></div><K1ErbStSchemaAlleV3 id={s}/></section>)}</div></>}
export default function K1ErbStPruefschemaV3(){return <><K1ErbStPruefschemaV2/><Stack titel="Fortsetzung der 2. Einheit · PDF-S. 151–457" lead="NNAS, Kosten-Gabel, Fall 15, BewG-Türöffner, Bedingungen, § 11/§ 12 sowie Darlehens- und Zinsfälle in der Quellenreihenfolge." bloecke={E2}/><Stack titel="3. Einheit · 451/451 tatsächliche PDF-Seiten" lead="Die dritte Einheit wird mit ihren Originalgabeln, Tabellen, Faktoren und Grundstücks-Flussbildern fortgeführt: stille Beteiligung, Nutzungen/Leistungen, Leibrenten und die vollständige Grundstücksbewertung bis Fall 27." bloecke={E3}/></>}
