import React from"react";
import"./ao.css";import"./erbst.css";import"./erbst2.css";
const H=({children,ton="blau"})=><span className={`erbst-hand erbst-hand--${ton}`}>{children}</span>;

function Hausrat(){return <div className="erbst-original erbst-paper erbst2-paper"><div className="erbst-schema-title">zu S · sachliche Steuerbefreiung § 13 Abs. 1 Nr. 1</div><div className="erbst2-house-head"><H ton="gruen">Hausrat</H><b>& andere bewegliche körperliche WG</b></div><div className="erbst2-house-grid"><section><h4>Steuerklasse I</h4><div className="erbst2-box"><b>Nr. 1a</b><span>Hausrat + Wäsche/Kleidung</span><strong>41.000 € FB</strong></div><div className="erbst2-box"><b>Nr. 1b</b><span>andere bewegliche körperliche WG</span><strong>12.000 € FB</strong></div></section><section><h4>Steuerklasse II / III</h4><div className="erbst2-box erbst2-box--wide"><b>Nr. 1c</b><span>Hausrat + andere bewegliche WG</span><strong>12.000 € FB</strong></div></section></div><div className="erbst2-note"><b>Beachte:</b> nicht befreit nach Quellenliste: Bargeld, Münzsammlung, unverarbeitete Edelmetalle. Freibetrag entfällt, wenn das WG herausgegeben werden muss.</div><div className="erbst2-exception">🍦 Keine Schuldenbegrenzung bei Hausrat & Pkw · R E 10.10 Abs. 2 S. 2</div></div>}
function Fall13(){return <div className="erbst-original erbst-paper erbst2-paper"><div className="erbst-schema-title">Fall 13 · W / S / V</div><div className="erbst2-wsv"><div><span>W</span><b>Fiat 500</b><strong>10.000 €</strong></div><div><span>S</span><b>§ 13 Abs. 1 Nr. 1b</b><strong>Freibetrag</strong></div><div><span>V</span><b>Werkstattrechnung</b><strong>500 €</strong></div></div><div className="erbst2-purple">R E 10.10 Abs. 2 S. 2 → Quellen-Ausnahme zur Schuldenbegrenzung</div></div>}
function Fall12(){return <div className="erbst-original erbst-paper erbst2-paper"><div className="erbst-schema-title">Fall 12 / Abwandlung · schwebender Erwerb</div><div className="erbst2-contract"><div><b>vor Tod</b><span>notarieller Kaufvertrag</span><span>Kaufpreis 300.000 €</span></div><strong>→</strong><div><b>nach Tod</b><span>Eigentumsumschreibung</span><span>Restkaufpreis + Erwerbsnebenkosten</span></div></div><div className="erbst2-wsv erbst2-wsv--small"><div><span>W</span><b>Stichtagsposition</b></div><div><span>S</span><b>–</b></div><div><span>V</span><b>Verpflichtung prüfen</b></div></div><p className="erbst-source-note">Die Quelle zeigt hier nur den Prüfansatz, keine vollständig ausgeschriebene Endlösung.</p></div>}
function Familienheim(){return <div className="erbst-original erbst-paper erbst2-paper"><div className="erbst-schema-title">§ 13 Abs. 1 Nr. 4a–4c · Familienheim</div><div className="erbst2-fh-root"><div className="erbst2-fh-branch"><H ton="braun">Ⓐ</H><h4>Erwerb von Todes wegen</h4><div className="erbst2-fh-split"><div><b>Nr. 4b</b><span>Ehegatte/Lebenspartner</span><strong>100 % steuerfrei</strong></div><div><b>Nr. 4c</b><span>Kinder</span><strong>bis 200 qm steuerfrei</strong><small>jeder weitere qm anteilig steuerpflichtig</small></div></div><div className="erbst2-ten">↓ 10 Jahre Selbstnutzung / Behalten<br/><small>oder zwingender Grund (z.B. Krankheit, Heim, Tod)</small></div></div><div className="erbst2-fh-branch"><H ton="lila">♥</H><h4>Lebzeitige Zuwendung</h4><div className="erbst2-fh-split"><div><b>Nr. 4a</b><span>Ehegatte/Lebenspartner</span><strong>100 % steuerfrei</strong><small>Quellenbild: keine 10-Jahres-Frist</small></div><div className="erbst2-no"><span>Kinder</span><strong>0 % über Nr. 4a</strong></div></div></div></div></div>}
function Wohnvermietung(){return <div className="erbst-original erbst-paper erbst2-paper"><div className="erbst-schema-title">§ 13d ErbStG · Steuerbefreiung für Wohnvermietung</div><div className="erbst2-13d-top"><b>Abs. 1</b><strong>10 % steuerfrei</strong><span>→ Ansatz mit 90 %</span></div><div className="erbst2-checklist"><b>Abs. 3 · Stichtagscheck</b><span>✓ zu Wohnzwecken vermietet</span><span>✓ begünstigte Lage</span><span>✓ nicht begünstigtes BV</span><span>✗ unentgeltliche Überlassung</span><span>✓ langfristig (&gt; 6 Monate) nach Quellenbild</span><span>Leerstand? → Vermietungsabsicht entscheidend · R E 13d Abs. 6 S. 4</span></div><div className="erbst2-stichtag"><div><b>Aufgabe Vermietung nach Erwerb?</b><strong>✓</strong></div><div><b>Vermietung erst nach Erwerb?</b><strong>✕</strong></div><em>Stichtagsprinzip!</em></div></div>}
function Verbindlichkeiten(){return <div className="erbst-original erbst-paper erbst2-paper"><div className="erbst-schema-title">zu V · Verbindlichkeiten, die zu einem WG gehören</div><div className="erbst2-liab-root"><section><H ton="gruen">Nachlassverbindlichkeiten</H><b>§ 10 Abs. 5 Nr. 1 + 2</b><div className="erbst2-liab-card"><strong>Nr. 1 „Erblasserschulden“</strong><span>zu Lebzeiten verursacht</span><span>Verpflichtung erforderlich</span><span>nur Schulden im PV (Quellenlogik)</span><small>direkt zuordenbar z.B.: Darlehen/Rest-KP, Sachleistungsverpflichtung, Werkstattrechnung</small></div><div className="erbst2-liab-card"><strong>Nr. 2 „Erbfallschulden“</strong><small>direkt zuordenbar z.B.: Wohnrechtsvermächtnis, Sachvermächtnis</small></div></section><div className="erbst2-bbb">B<br/>B<br/>B</div><section><H ton="lila">Gegenleistung / Auflagen</H><b>R E 7.4 Abs. 1 S. 2</b><div className="erbst2-liab-card"><strong>direkt zuordenbar z.B.</strong><span>Restschuld aus Erwerb übernommen</span><span>Wohnrecht / Nießbrauch</span></div></section></div></div>}
function Abzugsbegrenzung(){return <div className="erbst-original erbst-paper erbst2-paper"><div className="erbst-schema-title">Begrenzung des Abzugs · § 10 Abs. 6 / 6a</div><div className="erbst2-limit-root"><div><H ton="gruen">WG 100 % steuerfrei</H><small>z.B. Familienheim</small><strong>100 % Begrenzung auf 0 €</strong><b>§ 10 Abs. 6 S. 1</b></div><div className="erbst2-limit-ex">Ausn.: Hausrat + Pkw<br/><b>R E 10.10 Abs. 2 S. 2</b></div><div><H ton="braun">WG teilweise steuerfrei</H><small>z.B. § 13d</small><strong>teilweise Begrenzung</strong><b>§ 10 Abs. 6</b></div></div><div className="erbst2-6a"><b>§ 10 Abs. 6a</b><span>nicht direkt zuordenbare Schulden/Lasten → verhältnismäßige Zuordnung auf die Vermögensgegenstände</span></div></div>}
const SCHEMATA={"erbst2-hausrat":Hausrat,"erbst2-fall13":Fall13,"erbst2-fall12":Fall12,"erbst2-familienheim":Familienheim,"erbst2-13d":Wohnvermietung,"erbst2-verbindlichkeiten":Verbindlichkeiten,"erbst2-abzugsbegrenzung":Abzugsbegrenzung};
export const erbst2SchemaIds=Object.keys(SCHEMATA);
export default function K1ErbStSchemaEinheit2({id}){const C=SCHEMATA[id];return C?<C/>:null}
