import React from "react";
import "../data/k3-persg-originalfaelle-register.js";
import "./k3-persg-tag5.css";

const Box=({title,children,accent=false})=><section className={`p5-box ${accent?"p5-box--accent":""}`}>{title&&<h3>{title}</h3>}{children}</section>;
const Table=({head,rows})=><div className="p5-tablewrap"><table className="p5-table"><thead><tr>{head.map((x)=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>;

function Guide(){return <Box title="Klausurguide · 5. Einheit"><div className="p5-guidegrid">{[["1","Überführung / Übertragung einzelner WG","§ 6 Abs. 5 EStG"],["2","Einbringung betrieblicher Sachgesamtheiten","§ 24 UmwStG"],["3","Austritt von Gesellschaftern","§ 16 EStG"],["4","Gesellschafterwechsel","Ergänzungsbilanz"],["5","Realteilung","§ 16 Abs. 3 EStG"]].map(([n,t,l])=><article key={n}><b>{n}</b><span>{t}</span><small>{l}</small></article>)}</div></Box>}
function AustrittZivil(){return <Box title="Ausscheiden · Handels-/Zivilrecht"><div className="p5-callout"><b>1. Wertungspunkt</b><span>Austritt führt nicht zur Auflösung der Gesellschaft.</span></div><div className="p5-flow"><div><b>GbR</b><span>§ 728 BGB</span></div><i>→</i><div><b>OHG</b><span>§ 135 HGB</span></div><i>→</i><div><b>KG</b><span>§ 161 Abs. 2 HGB</span></div></div><div className="p5-callout p5-callout--accent"><b>Folge</b><span>Ausscheidender Gesellschafter hat einen Abfindungsanspruch; die Gesellschaft wird von den Verbleibenden fortgeführt.</span></div></Box>}
function Barabfindung(){return <Box title="Ausscheiden gegen Barabfindung"><div className="p5-flow"><div><b>Abfindung / VHP</b></div><i>−</i><div><b>Buchwert MU-Anteil</b></div><i>=</i><div><b>§ 16 Abs. 2 Gewinn</b></div></div><Table head={["A+B+C-OHG","Aktiva","Passiva"]} rows={[["Wirtschaftsgüter","120.000",""],["Kapital A","","40.000"],["Kapital B","","40.000"],["Kapital C","","40.000"]]} /><div className="p5-booking"><span>Beim Ausscheiden:</span><b>Kapital C</b><i>→</i><b>Abfindungsverbindlichkeit C</b></div></Box>}
function AustrittFall(){return <Box title="Austrittsfall · Reserven, § 6b und AfA"><div className="p5-three"><article><span>1</span><b>Auseinandersetzungsbilanz</b><small>Teilwerte ./. Buchwerte = stille Reserven</small></article><article><span>2</span><b>§ 6b-Rücklage</b><small>auf C entfallender Anteil wird in der Aufgabe aufgelöst</small></article><article><span>3</span><b>AfA-Fortführung</b><small>Eröffnungsbilanz 01.01.2025 → Schlussbilanz 31.12.2025</small></article></div><div className="p5-callout"><b>Klausurtechnik</b><span>Nicht pauschal aufwerten: jedes Wirtschaftsgut, jede stille Reserve und jede Restnutzungsdauer gesondert fortführen.</span></div></Box>}
function Sachwert(){return <Box title="Ausscheiden gegen Sachwert"><div className="p5-facts"><span>Abfindungsverbindlichkeit C <b>130.000 €</b></span><span>hingegebenes Grubo 2 <b>110.000 €</b></span><span>Differenz <b>20.000 €</b></span></div><div className="p5-flow"><div><b>§ 16 beim C</b><span>Ausscheiden / VHP</span></div><i>+</i><div><b>§ 6 Abs. 5</b><span>Übertragung des Wirtschaftsguts</span></div></div><div className="p5-callout p5-callout--accent"><b>Doppelte Prüfung</b><span>Personenebene des Ausscheidenden und Sachwertübertragung nicht miteinander vermischen.</span></div></Box>}
function Wechsel(){return <Box title="Gesellschafterwechsel C → D"><div className="p5-parties"><div><b>C</b><small>verkauft 1/4 MU-Anteil</small></div><span>100.000 € ↔ MU-Anteil</span><div><b>D</b><small>Erwerber</small></div></div><Table head={["ABC-OHG 31.12.2024","Aktiva","Passiva"]} rows={[["Grubo","100.000",""],["Gebäude","120.000",""],["Maschine","100.000",""],["Forderungen","10.000",""],["Bank","90.000",""],["Kapital A / B / C","","150.000 / 150.000 / 100.000"],["Verbindlichkeiten","","20.000"]]} /><div className="p5-two"><article><b>Gesamthandsbilanz</b><p>Buchwerte werden durch den Anteilskauf nicht hochgesetzt.</p></article><article><b>Ergänzungsbilanz D</b><p>Kaufpreisbedingte Mehr-/Minderwerte werden D individuell zugerechnet und über Mehr-/Minder-AfA fortgeführt.</p></article></div></Box>}
function RealteilungMaster(){return <Box title="Realteilung · § 16 Abs. 3 S. 2 EStG"><div className="p5-real"><div className="p5-real__top"><b>A+B-OHG</b><small>Mitunternehmerschaft</small></div><div className="p5-real__arrows"><span>↙</span><span>↘</span></div><div className="p5-real__bottom"><article><b>EU A</b><small>Buchwertfortführung</small></article><article><b>Betrieb / PV B</b><small>nach Gegenstand prüfen</small></article></div></div><div className="p5-two"><article><b>Echte Realteilung</b><p>Mitunternehmerschaft wird aufgegeben/aufgelöst; Vermögen geht auf die Realteiler über.</p></article><article><b>Unechte Realteilung</b><p>Ein Mitunternehmer scheidet gegen Sachwerte aus; die Mitunternehmerschaft wird von den Verbleibenden fortgeführt.</p></article></div></Box>}
function Sperre(){return <Box title="Realteilung · Sperrfrist und Körperschaftsklausel"><div className="p5-steps"><div><b>Satz 2</b><span>Buchwertfortführung</span></div><div><b>Satz 3</b><span>Einzel-WG: rückwirkender gemeiner Wert bei schädlicher Veräußerung/Entnahme innerhalb der Sperrfrist</span></div><div><b>Satz 4</b><span>zusätzliche Einschränkung bei Übertragung auf Körperschaft/Personenvereinigung/Vermögensmasse</span></div></div><div className="p5-callout"><b>Fristgedanke</b><span>Quelle: Sperrfrist endet drei Jahre nach Abgabe der Steuererklärung der Mitunternehmerschaft für den Veranlagungszeitraum der Realteilung.</span></div></Box>}
function RealteilungFall(){return <Box title="Realteilung · Wertverschiebung und Ausgleich"><Table head={["Teilwerte / gemeine Werte","Betrag"]} rows={[["Grund und Boden","400.000 €"],["Gebäude","900.000 €"],["Maschinen","460.000 €"],["Betriebsausstattung","280.000 €"],["Beteiligung V-GmbH","380.000 €"],["übrige Aktiva","430.000 €"],["Firmenwert","450.000 €"],["Summe","3.300.000 €"]]} /><div className="p5-comp"><article><b>TB 1</b><strong>530.000 €</strong></article><span>↔ Wertausgleich</span><article><b>TB 2</b><strong>610.000 €</strong><small>Quellenrechnung: 40.000 € entgeltliche Komponente / 570.000 € übriger Teil</small></article></div><div className="p5-callout p5-callout--accent"><b>Prüfpunkt</b><span>Ausgleichszahlung nur insoweit als entgeltlichen Vorgang isolieren; restliche Realteilung im Buchwertregime fortführen.</span></div></Box>}

const visuals={"p5-guide":Guide,"p5-austritt-zivil":AustrittZivil,"p5-austritt-master":Barabfindung,"p5-barabfindung":Barabfindung,"p5-austritt-fall":AustrittFall,"p5-sachwert":Sachwert,"p5-wechsel":Wechsel,"p5-realteilung-master":RealteilungMaster,"p5-realteilung-sperre":Sperre,"p5-realteilung-fall":RealteilungFall};
export default function K3PersGTag5Visuals({type}){const C=visuals[type];return C?<C/>:null;}
