name: Validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run check:fallsammlung
      - run: npm run check:fallsammlung-format
      - run: npm run check:hausaufgaben
      - run: npm run check:k1-ao-einheit-1
      - run: npm run check:k1-ao-einheit-2
      - run: npm run check:k1-ao-einheit-3
      - run: npm run check:k1-ao-einheit-4
      - run: npm run check:k1-ao-einheit-5
      - run: npm run build
